-- Este script sincroniza el catálogo de ejercicios de GymPartner
-- con los 92 ejercicios premium que cuentan con imágenes sin fondo de forma segura.

-- 1. Eliminar de forma segura ejercicios obsoletos que NO estén siendo referenciados en ningún historial o rutina
DELETE FROM public.exercises 
WHERE name NOT IN ('Abdominales Inversos', 'Russian Twist', 'Crunch Abdominal', 'Crunch en Máquina', 'Crunch en Polea Alta', 'Elevación de Piernas (Colgado)', 'Plancha (Plank)', 'Curl Martillo (Polea/Cuerda)', 'Curl Martillo (Mancuernas)', 'Curl de Bíceps (Mancuernas)', 'Curl de Bíceps con Barra', 'Curl de Bíceps Bayoneta', 'Curl de Bíceps en Polea', 'Curl Predicador (Barra)', 'Curl Predicador (Máquina)', 'Curl Araña (Spider Curl)', 'Bicicleta Estática', 'Elíptica', 'Cinta de Correr', 'Escaladora (Stairmaster)', 'Remo (Concept2)', 'Salto de Cuerda', 'Dominadas Asistidas (Máquina)', 'Dominadas (Pullups)', 'Jalón al Pecho (Agarre Estrecho)', 'Jalón al Pecho (Polea Alta)', 'Peso Muerto (Deadlift)', 'Pull-Over en Polea', 'Remo con Barra Pendlay', 'Remo con Barra Yates', 'Remo con Mancuerna (Unilateral)', 'Remo en Máquina (Pecho Apoyado)', 'Remo en T (Barra/Máquina)', 'Remo Gironda (Polea Baja)', 'Hip Thrust (Barra Libre)', 'Hip Thrust (Máquina)', 'Hip Thrust en Smith', 'Patada de Glúteo (Polea)', 'Patada de Glúteo (Máquina)', 'Elevaciones Frontales (Mancuernas)', 'Elevaciones Frontales (Polea)', 'Elevaciones Laterales (Mancuernas)', 'Elevaciones Laterales (Máquina)', 'Elevaciones Laterales (Polea)', 'Face Pull', 'Peck Deck Invertido', 'Press de Hombros (Máquina)', 'Press Militar (Barra)', 'Press Militar (Mancuernas)', 'Pájaros / Vuelos (Mancuernas)', 'Crossover en Polea Baja', 'Cruce de Poleas (Crossover Alto)', 'Peck Deck (Mariposa)', 'Fondos (Dips)', 'Fondos Asistidos (Pecho)', 'Press Banca Plano (Barra)', 'Press Banca Plano (Mancuernas)', 'Press Declinado (Barra)', 'Press Declinado (Máquina)', 'Press Declinado (Mancuernas)', 'Press Inclinado (Barra)', 'Press Inclinado (Mancuernas)', 'Press Inclinado (Polea/Cable)', 'Press Inclinado (Máquina)', 'Smith Press Inclinado', 'Press de Pecho (Máquina)', 'Press Plano (Polea/Cable)', 'Smith Press Plano', 'Curl Femoral Sentado (Máquina)', 'Curl Femoral Tumbado (Máquina)', 'Extensiones de Cuádriceps', 'Good Mornings (Buenos Días)', 'Peso Muerto Rumano (Barra)', 'Peso Muerto Rumano (Mancuernas)', 'Prensa de Piernas (45°)', 'Sentadilla Búlgara', 'Sentadilla Frontal', 'Sentadilla Hack (Máquina)', 'Sentadilla Libre (Barra)', 'Zancadas en Smith', 'Zancadas / Lunges (Barra)', 'Zancadas / Lunges (Mancuernas)', 'Copa a dos manos (Mancuerna)', 'Copa a una mano (Mancuerna)', 'Extensiones de Tríceps (Barra Recta)', 'Extensiones de Tríceps (Polea/Cuerda)', 'Extensiones de Tríceps (Polea)', 'Fondos en Bancos', 'Fondos en Paralelas', 'Patada de Tríceps (Mancuerna)', 'Press Francés (Barra Z)', 'Press Francés (Mancuernas)')
  AND id NOT IN (SELECT DISTINCT exercise_id FROM public.workout_logs WHERE exercise_id IS NOT NULL)
  AND id NOT IN (SELECT DISTINCT exercise_id FROM public.routine_exercises WHERE exercise_id IS NOT NULL);

-- 2. Insertar los nuevos ejercicios únicamente si no existen previamente por nombre
INSERT INTO public.exercises (name, target_muscle_group)
SELECT new_ex.name, new_ex.target_muscle_group
FROM (
    VALUES
    ('Abdominales Inversos', 'Abdominales'),
    ('Russian Twist', 'Abdominales'),
    ('Crunch Abdominal', 'Abdominales'),
    ('Crunch en Máquina', 'Abdominales'),
    ('Crunch en Polea Alta', 'Abdominales'),
    ('Elevación de Piernas (Colgado)', 'Abdominales'),
    ('Plancha (Plank)', 'Abdominales'),
    ('Curl Martillo (Polea/Cuerda)', 'Bíceps'),
    ('Curl Martillo (Mancuernas)', 'Bíceps'),
    ('Curl de Bíceps (Mancuernas)', 'Bíceps'),
    ('Curl de Bíceps con Barra', 'Bíceps'),
    ('Curl de Bíceps Bayoneta', 'Bíceps'),
    ('Curl de Bíceps en Polea', 'Bíceps'),
    ('Curl Predicador (Barra)', 'Bíceps'),
    ('Curl Predicador (Máquina)', 'Bíceps'),
    ('Curl Araña (Spider Curl)', 'Bíceps'),
    ('Bicicleta Estática', 'Cardio'),
    ('Elíptica', 'Cardio'),
    ('Cinta de Correr', 'Cardio'),
    ('Escaladora (Stairmaster)', 'Cardio'),
    ('Remo (Concept2)', 'Cardio'),
    ('Salto de Cuerda', 'Cardio'),
    ('Dominadas Asistidas (Máquina)', 'Espalda'),
    ('Dominadas (Pullups)', 'Espalda'),
    ('Jalón al Pecho (Agarre Estrecho)', 'Espalda'),
    ('Jalón al Pecho (Polea Alta)', 'Espalda'),
    ('Peso Muerto (Deadlift)', 'Espalda'),
    ('Pull-Over en Polea', 'Espalda'),
    ('Remo con Barra Pendlay', 'Espalda'),
    ('Remo con Barra Yates', 'Espalda'),
    ('Remo con Mancuerna (Unilateral)', 'Espalda'),
    ('Remo en Máquina (Pecho Apoyado)', 'Espalda'),
    ('Remo en T (Barra/Máquina)', 'Espalda'),
    ('Remo Gironda (Polea Baja)', 'Espalda'),
    ('Hip Thrust (Barra Libre)', 'Glúteos'),
    ('Hip Thrust (Máquina)', 'Glúteos'),
    ('Hip Thrust en Smith', 'Glúteos'),
    ('Patada de Glúteo (Polea)', 'Glúteos'),
    ('Patada de Glúteo (Máquina)', 'Glúteos'),
    ('Elevaciones Frontales (Mancuernas)', 'Hombro'),
    ('Elevaciones Frontales (Polea)', 'Hombro'),
    ('Elevaciones Laterales (Mancuernas)', 'Hombro'),
    ('Elevaciones Laterales (Máquina)', 'Hombro'),
    ('Elevaciones Laterales (Polea)', 'Hombro'),
    ('Face Pull', 'Hombro'),
    ('Peck Deck Invertido', 'Hombro'),
    ('Press de Hombros (Máquina)', 'Hombro'),
    ('Press Militar (Barra)', 'Hombro'),
    ('Press Militar (Mancuernas)', 'Hombro'),
    ('Pájaros / Vuelos (Mancuernas)', 'Hombro'),
    ('Crossover en Polea Baja', 'Pecho'),
    ('Cruce de Poleas (Crossover Alto)', 'Pecho'),
    ('Peck Deck (Mariposa)', 'Pecho'),
    ('Fondos (Dips)', 'Pecho'),
    ('Fondos Asistidos (Pecho)', 'Pecho'),
    ('Press Banca Plano (Barra)', 'Pecho'),
    ('Press Banca Plano (Mancuernas)', 'Pecho'),
    ('Press Declinado (Barra)', 'Pecho'),
    ('Press Declinado (Máquina)', 'Pecho'),
    ('Press Declinado (Mancuernas)', 'Pecho'),
    ('Press Inclinado (Barra)', 'Pecho'),
    ('Press Inclinado (Mancuernas)', 'Pecho'),
    ('Press Inclinado (Polea/Cable)', 'Pecho'),
    ('Press Inclinado (Máquina)', 'Pecho'),
    ('Smith Press Inclinado', 'Pecho'),
    ('Press de Pecho (Máquina)', 'Pecho'),
    ('Press Plano (Polea/Cable)', 'Pecho'),
    ('Smith Press Plano', 'Pecho'),
    ('Curl Femoral Sentado (Máquina)', 'Pierna'),
    ('Curl Femoral Tumbado (Máquina)', 'Pierna'),
    ('Extensiones de Cuádriceps', 'Pierna'),
    ('Good Mornings (Buenos Días)', 'Pierna'),
    ('Peso Muerto Rumano (Barra)', 'Pierna'),
    ('Peso Muerto Rumano (Mancuernas)', 'Pierna'),
    ('Prensa de Piernas (45°)', 'Pierna'),
    ('Sentadilla Búlgara', 'Pierna'),
    ('Sentadilla Frontal', 'Pierna'),
    ('Sentadilla Hack (Máquina)', 'Pierna'),
    ('Sentadilla Libre (Barra)', 'Pierna'),
    ('Zancadas en Smith', 'Pierna'),
    ('Zancadas / Lunges (Barra)', 'Pierna'),
    ('Zancadas / Lunges (Mancuernas)', 'Pierna'),
    ('Copa a dos manos (Mancuerna)', 'Tríceps'),
    ('Copa a una mano (Mancuerna)', 'Tríceps'),
    ('Extensiones de Tríceps (Barra Recta)', 'Tríceps'),
    ('Extensiones de Tríceps (Polea/Cuerda)', 'Tríceps'),
    ('Extensiones de Tríceps (Polea)', 'Tríceps'),
    ('Fondos en Bancos', 'Tríceps'),
    ('Fondos en Paralelas', 'Tríceps'),
    ('Patada de Tríceps (Mancuerna)', 'Tríceps'),
    ('Press Francés (Barra Z)', 'Tríceps'),
    ('Press Francés (Mancuernas)', 'Tríceps')
) AS new_ex(name, target_muscle_group)
WHERE NOT EXISTS (
    SELECT 1 FROM public.exercises e 
    WHERE e.name = new_ex.name
);
