// AUTO-GENERATED by scripts/generateCatalog.mjs — DO NOT EDIT MANUALLY
// Run "npm run catalog" to regenerate after adding/moving images.
// Generated: 2026-06-30T20:59:40.228Z
//
// HOW TO ADD AN EXERCISE:
//   1. Put the image in public/ejercicioimg/ejercicios/<MuscleFolder>/<Name>.png  (standalone)
//   2. Or create a folder: <MuscleFolder>/<ExerciseName>/<Variant>.png            (with variants)
//   3. Run: npm run catalog

export interface CatalogVariant {
  id: string;
  label: string;
  seedName: string;
  imagePath: string;
  isLocked: boolean;
}

export interface CatalogExercise {
  id: string;
  name: string;
  muscle: string;
  icon: string;
  metrics: {
    weight: boolean;
    reps: boolean;
    time: boolean;
    distance: boolean;
    rpe: boolean;
  };
  imagePath: string;
  isLocked: boolean;
  variants: CatalogVariant[];
}

export const CATALOG_DATA: CatalogExercise[] = [
  {
    "id": "crunch_abdomen",
    "name": "Crunch",
    "muscle": "ABDOMINALES",
    "icon": "🥨",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Estándar.png",
    "isLocked": false,
    "variants": [
      {
        "id": "estandar",
        "label": "Estándar",
        "seedName": "Crunch (Estándar)",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Estándar.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "label": "Máquina",
        "seedName": "Crunch (Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Máquina.png",
        "isLocked": false
      },
      {
        "id": "polea_alta",
        "label": "Polea Alta",
        "seedName": "Crunch (Polea Alta)",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Polea Alta.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "crunch_inverso_abdomen",
    "name": "Crunch Inverso",
    "muscle": "ABDOMINALES",
    "icon": "🥨",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Inverso/Encogimientos de Rodillas.png",
    "isLocked": false,
    "variants": [
      {
        "id": "encogimientos_de_rodillas",
        "label": "Encogimientos de Rodillas",
        "seedName": "Crunch Inverso (Encogimientos de Rodillas)",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Inverso/Encogimientos de Rodillas.png",
        "isLocked": false
      },
      {
        "id": "talones",
        "label": "Talones",
        "seedName": "Crunch Inverso (Talones)",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Inverso/Talones.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "crunch_oblicuo_abdomen",
    "name": "Crunch Oblicuo",
    "muscle": "ABDOMINALES",
    "icon": "🥨",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Oblicuo/Encogimientos de Rodillas.png",
    "isLocked": false,
    "variants": [
      {
        "id": "encogimientos_de_rodillas",
        "label": "Encogimientos de Rodillas",
        "seedName": "Crunch Oblicuo (Encogimientos de Rodillas)",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Oblicuo/Encogimientos de Rodillas.png",
        "isLocked": false
      },
      {
        "id": "estandar",
        "label": "Estándar",
        "seedName": "Crunch Oblicuo (Estándar)",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Oblicuo/Estándar.png",
        "isLocked": false
      },
      {
        "id": "gemini_generated_image_2mgqe52mgqe52mgq",
        "label": "Gemini_Generated_Image_2mgqe52mgqe52mgq",
        "seedName": "Crunch Oblicuo (Gemini_Generated_Image_2mgqe52mgqe52mgq)",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Oblicuo/ocultos/Gemini_Generated_Image_2mgqe52mgqe52mgq-Photoroom.png",
        "isLocked": true
      }
    ]
  },
  {
    "id": "elevacion_de_piernas_abdomen",
    "name": "Elevación de Piernas",
    "muscle": "ABDOMINALES",
    "icon": "🥨",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Elevación de Piernas.png",
    "isLocked": false,
    "variants": [
      {
        "id": "elevacion_de_piernas",
        "label": "Elevación de Piernas",
        "seedName": "Elevación de Piernas",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Elevación de Piernas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "plancha_abdomen",
    "name": "Plancha",
    "muscle": "ABDOMINALES",
    "icon": "🥨",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Plancha/Con Flexión.png",
    "isLocked": false,
    "variants": [
      {
        "id": "con_flexion",
        "label": "Con Flexión",
        "seedName": "Plancha (Con Flexión)",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Plancha/Con Flexión.png",
        "isLocked": false
      },
      {
        "id": "estatica",
        "label": "Estática",
        "seedName": "Plancha (Estática)",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Plancha/Estática.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "russian_twist_abdomen",
    "name": "Russian Twist",
    "muscle": "ABDOMINALES",
    "icon": "🥨",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Russian Twist.png",
    "isLocked": false,
    "variants": [
      {
        "id": "russian_twist",
        "label": "Russian Twist",
        "seedName": "Russian Twist",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Russian Twist.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_de_muneca_antebrazo",
    "name": "Curl de Muñeca",
    "muscle": "ANTEBRAZO",
    "icon": "🦾",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Curl de Muñeca.png",
    "isLocked": false,
    "variants": [
      {
        "id": "curl_de_muneca",
        "label": "Curl de Muñeca",
        "seedName": "Curl de Muñeca",
        "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Curl de Muñeca.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "extension_de_muneca_antebrazo",
    "name": "Extensión de Muñeca",
    "muscle": "ANTEBRAZO",
    "icon": "🦾",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Extensión de Muñeca/Invertido.png",
    "isLocked": false,
    "variants": [
      {
        "id": "invertido",
        "label": "Invertido",
        "seedName": "Extensión de Muñeca (Invertido)",
        "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Extensión de Muñeca/Invertido.png",
        "isLocked": false
      },
      {
        "id": "supino",
        "label": "Supino",
        "seedName": "Extensión de Muñeca (Supino)",
        "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Extensión de Muñeca/Supino.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_bayoneta_biceps",
    "name": "Curl Bayoneta",
    "muscle": "BÍCEPS",
    "icon": "💪",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Bayoneta.png",
    "isLocked": false,
    "variants": [
      {
        "id": "curl_bayoneta",
        "label": "Curl Bayoneta",
        "seedName": "Curl Bayoneta",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Bayoneta.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_normal_biceps",
    "name": "Curl Normal",
    "muscle": "BÍCEPS",
    "icon": "💪",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Normal/Barra.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra",
        "label": "Barra",
        "seedName": "Curl Normal (Barra)",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Normal/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Curl Normal (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Normal/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "polea_alta",
        "label": "Polea Alta",
        "seedName": "Curl Normal (Polea Alta)",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Normal/Polea Alta.png",
        "isLocked": false
      },
      {
        "id": "polea_baja",
        "label": "Polea Baja",
        "seedName": "Curl Normal (Polea Baja)",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Normal/Polea Baja.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_spider_biceps",
    "name": "Curl Spider",
    "muscle": "BÍCEPS",
    "icon": "💪",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Spider.png",
    "isLocked": false,
    "variants": [
      {
        "id": "curl_spider",
        "label": "Curl Spider",
        "seedName": "Curl Spider",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Spider.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "martillo_biceps",
    "name": "Martillo",
    "muscle": "BÍCEPS",
    "icon": "💪",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Cuerda.png",
    "isLocked": false,
    "variants": [
      {
        "id": "cuerda",
        "label": "Cuerda",
        "seedName": "Martillo (Cuerda)",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Cuerda.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Martillo (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Mancuernas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "predicador_biceps",
    "name": "Predicador",
    "muscle": "BÍCEPS",
    "icon": "💪",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/Barra.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra",
        "label": "Barra",
        "seedName": "Predicador (Barra)",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/Barra.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "label": "Máquina",
        "seedName": "Predicador (Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/Máquina.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "caminadoras_cardio",
    "name": "Caminadoras",
    "muscle": "CARDIO",
    "icon": "🚴",
    "metrics": {
      "weight": false,
      "reps": false,
      "time": true,
      "distance": true,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Bicicleta.png",
    "isLocked": false,
    "variants": [
      {
        "id": "bicicleta",
        "label": "Bicicleta",
        "seedName": "Caminadoras (Bicicleta)",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Bicicleta.png",
        "isLocked": false
      },
      {
        "id": "cinta",
        "label": "Cinta",
        "seedName": "Caminadoras (Cinta)",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Cinta.png",
        "isLocked": false
      },
      {
        "id": "eliptica",
        "label": "Elíptica",
        "seedName": "Caminadoras (Elíptica)",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Elíptica.png",
        "isLocked": false
      },
      {
        "id": "escaladora",
        "label": "Escaladora",
        "seedName": "Caminadoras (Escaladora)",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Escaladora.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "remo_cardio",
    "name": "Remo",
    "muscle": "CARDIO",
    "icon": "🚴",
    "metrics": {
      "weight": false,
      "reps": false,
      "time": true,
      "distance": true,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Remo.png",
    "isLocked": false,
    "variants": [
      {
        "id": "remo",
        "label": "Remo",
        "seedName": "Remo",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Remo.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "salto_a_la_cuerda_cardio",
    "name": "Salto a la Cuerda",
    "muscle": "CARDIO",
    "icon": "🚴",
    "metrics": {
      "weight": false,
      "reps": false,
      "time": true,
      "distance": true,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Salto a la Cuerda.png",
    "isLocked": false,
    "variants": [
      {
        "id": "salto_a_la_cuerda",
        "label": "Salto a la Cuerda",
        "seedName": "Salto a la Cuerda",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Salto a la Cuerda.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "arnes_de_cuello_cuello",
    "name": "Arnés de Cuello",
    "muscle": "CUELLO",
    "icon": "💆",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Arnés de Cuello.png",
    "isLocked": false,
    "variants": [
      {
        "id": "arnes_de_cuello",
        "label": "Arnés de Cuello",
        "seedName": "Arnés de Cuello",
        "imagePath": "/ejercicioimg/ejercicios/Cuello/Arnés de Cuello.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "extension_con_disco_cuello",
    "name": "Extensión con Disco",
    "muscle": "CUELLO",
    "icon": "💆",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Extensión con Disco.png",
    "isLocked": false,
    "variants": [
      {
        "id": "extension_con_disco",
        "label": "Extensión con Disco",
        "seedName": "Extensión con Disco",
        "imagePath": "/ejercicioimg/ejercicios/Cuello/Extensión con Disco.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "flexion_con_disco_cuello",
    "name": "Flexión con Disco",
    "muscle": "CUELLO",
    "icon": "💆",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Flexión con Disco.png",
    "isLocked": false,
    "variants": [
      {
        "id": "flexion_con_disco",
        "label": "Flexión con Disco",
        "seedName": "Flexión con Disco",
        "imagePath": "/ejercicioimg/ejercicios/Cuello/Flexión con Disco.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "dominadas_espalda",
    "name": "Dominadas",
    "muscle": "ESPALDA",
    "icon": "🚣",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Asistida.png",
    "isLocked": false,
    "variants": [
      {
        "id": "asistida",
        "label": "Asistida",
        "seedName": "Dominadas (Asistida)",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Asistida.png",
        "isLocked": false
      },
      {
        "id": "libre",
        "label": "Libre",
        "seedName": "Dominadas (Libre)",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Libre.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "jalon_espalda",
    "name": "Jalón",
    "muscle": "ESPALDA",
    "icon": "🚣",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalón/Agarre Estrecho.png",
    "isLocked": false,
    "variants": [
      {
        "id": "agarre_estrecho",
        "label": "Agarre Estrecho",
        "seedName": "Jalón (Agarre Estrecho)",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalón/Agarre Estrecho.png",
        "isLocked": false
      },
      {
        "id": "polea_alta",
        "label": "Polea Alta",
        "seedName": "Jalón (Polea Alta)",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalón/Polea Alta.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "pull_over_polea_espalda",
    "name": "Pull Over Polea",
    "muscle": "ESPALDA",
    "icon": "🚣",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Pull Over Polea.png",
    "isLocked": false,
    "variants": [
      {
        "id": "pull_over_polea",
        "label": "Pull Over Polea",
        "seedName": "Pull Over Polea",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Pull Over Polea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "remo_con_barra_espalda",
    "name": "Remo con Barra",
    "muscle": "ESPALDA",
    "icon": "🚣",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo con Barra/Barra Pendlay.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra_pendlay",
        "label": "Barra Pendlay",
        "seedName": "Remo con Barra (Barra Pendlay)",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo con Barra/Barra Pendlay.png",
        "isLocked": false
      },
      {
        "id": "barra_yates",
        "label": "Barra Yates",
        "seedName": "Remo con Barra (Barra Yates)",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo con Barra/Barra Yates.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Remo con Barra (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo con Barra/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "t_barra",
        "label": "T-Barra",
        "seedName": "Remo con Barra (T-Barra)",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo con Barra/T-Barra.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "remo_sentado_espalda",
    "name": "Remo Sentado",
    "muscle": "ESPALDA",
    "icon": "🚣",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo Sentado/Gironda.png",
    "isLocked": false,
    "variants": [
      {
        "id": "gironda",
        "label": "Gironda",
        "seedName": "Remo Sentado (Gironda)",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo Sentado/Gironda.png",
        "isLocked": false
      },
      {
        "id": "pecho_apoyado",
        "label": "Pecho Apoyado",
        "seedName": "Remo Sentado (Pecho Apoyado)",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo Sentado/Pecho Apoyado.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevacion_de_pie_gemelos",
    "name": "Elevación de Pie",
    "muscle": "PANTORRILLAS",
    "icon": "🦵",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Gemelos/Elevación de Pie/Máquina.png",
    "isLocked": false,
    "variants": [
      {
        "id": "maquina",
        "label": "Máquina",
        "seedName": "Elevación de Pie (Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/Gemelos/Elevación de Pie/Máquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "label": "Smith",
        "seedName": "Elevación de Pie (Smith)",
        "imagePath": "/ejercicioimg/ejercicios/Gemelos/Elevación de Pie/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevacion_sentado_gemelos",
    "name": "Elevación Sentado",
    "muscle": "PANTORRILLAS",
    "icon": "🦵",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Gemelos/Elevación Sentado.png",
    "isLocked": false,
    "variants": [
      {
        "id": "elevacion_sentado",
        "label": "Elevación Sentado",
        "seedName": "Elevación Sentado",
        "imagePath": "/ejercicioimg/ejercicios/Gemelos/Elevación Sentado.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "abduccion_de_cadera_gluteo",
    "name": "Abducción de Cadera",
    "muscle": "GLÚTEOS",
    "icon": "🍑",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Abducción de Cadera.png",
    "isLocked": false,
    "variants": [
      {
        "id": "abduccion_de_cadera",
        "label": "Abducción de Cadera",
        "seedName": "Abducción de Cadera",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Abducción de Cadera.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "caminata_de_pato_gluteo",
    "name": "Caminata de Pato",
    "muscle": "GLÚTEOS",
    "icon": "🍑",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Caminata de Pato.png",
    "isLocked": false,
    "variants": [
      {
        "id": "caminata_de_pato",
        "label": "Caminata de Pato",
        "seedName": "Caminata de Pato",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Caminata de Pato.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "columpios_kettlebell_gluteo",
    "name": "Columpios Kettlebell",
    "muscle": "GLÚTEOS",
    "icon": "🍑",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Columpios Kettlebell.png",
    "isLocked": false,
    "variants": [
      {
        "id": "columpios_kettlebell",
        "label": "Columpios Kettlebell",
        "seedName": "Columpios Kettlebell",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Columpios Kettlebell.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevacion_de_rana_gluteo",
    "name": "Elevación de Rana",
    "muscle": "GLÚTEOS",
    "icon": "🍑",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Elevación de Rana.png",
    "isLocked": false,
    "variants": [
      {
        "id": "elevacion_de_rana",
        "label": "Elevación de Rana",
        "seedName": "Elevación de Rana",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Elevación de Rana.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "hip_thrust_gluteo",
    "name": "Hip Thrust",
    "muscle": "GLÚTEOS",
    "icon": "🍑",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Hip Thrust/Barra.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra",
        "label": "Barra",
        "seedName": "Hip Thrust (Barra)",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Hip Thrust/Barra.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "label": "Máquina",
        "seedName": "Hip Thrust (Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Hip Thrust/Máquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "label": "Smith",
        "seedName": "Hip Thrust (Smith)",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Hip Thrust/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "patada_de_gluteo_gluteo",
    "name": "Patada de Glúteo",
    "muscle": "GLÚTEOS",
    "icon": "🍑",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada de Glúteo/Máquina.png",
    "isLocked": false,
    "variants": [
      {
        "id": "maquina",
        "label": "Máquina",
        "seedName": "Patada de Glúteo (Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada de Glúteo/Máquina.png",
        "isLocked": false
      },
      {
        "id": "polea",
        "label": "Polea",
        "seedName": "Patada de Glúteo (Polea)",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada de Glúteo/Polea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "step_up_gluteo",
    "name": "Step Up",
    "muscle": "GLÚTEOS",
    "icon": "🍑",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Step Up.png",
    "isLocked": false,
    "variants": [
      {
        "id": "step_up",
        "label": "Step Up",
        "seedName": "Step Up",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Step Up.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevaciones_frontales_hombro",
    "name": "Elevaciones Frontales",
    "muscle": "HOMBRO",
    "icon": "🐦",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Frontales/Disco Dos Manos.png",
    "isLocked": false,
    "variants": [
      {
        "id": "disco_dos_manos",
        "label": "Disco Dos Manos",
        "seedName": "Elevaciones Frontales (Disco Dos Manos)",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Frontales/Disco Dos Manos.png",
        "isLocked": false
      },
      {
        "id": "mancuerna_dos_manos",
        "label": "Mancuerna Dos Manos",
        "seedName": "Elevaciones Frontales (Mancuerna Dos Manos)",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Frontales/Mancuerna Dos Manos.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Elevaciones Frontales (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Frontales/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "polea",
        "label": "Polea",
        "seedName": "Elevaciones Frontales (Polea)",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Frontales/Polea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevaciones_laterales_hombro",
    "name": "Elevaciones Laterales",
    "muscle": "HOMBRO",
    "icon": "🐦",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Laterales/Mancuernas.png",
    "isLocked": false,
    "variants": [
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Elevaciones Laterales (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Laterales/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "label": "Máquina",
        "seedName": "Elevaciones Laterales (Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Laterales/Máquina.png",
        "isLocked": false
      },
      {
        "id": "polea",
        "label": "Polea",
        "seedName": "Elevaciones Laterales (Polea)",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Laterales/Polea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "face_pull_hombro",
    "name": "Face Pull",
    "muscle": "HOMBRO",
    "icon": "🐦",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Face Pull.png",
    "isLocked": false,
    "variants": [
      {
        "id": "face_pull",
        "label": "Face Pull",
        "seedName": "Face Pull",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Face Pull.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "peck_deck_invertido_hombro",
    "name": "Peck Deck Invertido",
    "muscle": "HOMBRO",
    "icon": "🐦",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Peck Deck Invertido.png",
    "isLocked": false,
    "variants": [
      {
        "id": "peck_deck_invertido",
        "label": "Peck Deck Invertido",
        "seedName": "Peck Deck Invertido",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Peck Deck Invertido.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "press_militar_hombro",
    "name": "Press Militar",
    "muscle": "HOMBRO",
    "icon": "🐦",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Press Militar/Barra.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra",
        "label": "Barra",
        "seedName": "Press Militar (Barra)",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Press Militar/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Press Militar (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Press Militar/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "label": "Máquina",
        "seedName": "Press Militar (Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Press Militar/Máquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "label": "Smith",
        "seedName": "Press Militar (Smith)",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Press Militar/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "pajaros_vuelos_posterior_hombro",
    "name": "Pájaros Vuelos Posterior",
    "muscle": "HOMBRO",
    "icon": "🐦",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Pájaros Vuelos Posterior.png",
    "isLocked": false,
    "variants": [
      {
        "id": "pajaros_vuelos_posterior",
        "label": "Pájaros Vuelos Posterior",
        "seedName": "Pájaros Vuelos Posterior",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Pájaros Vuelos Posterior.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "buenos_dias_isquiotibiales",
    "name": "Buenos Días",
    "muscle": "ISQUIOTIBIALES",
    "icon": "🎋",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Buenos Días.png",
    "isLocked": false,
    "variants": [
      {
        "id": "buenos_dias",
        "label": "Buenos Días",
        "seedName": "Buenos Días",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Buenos Días.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_femoral_sentado_isquiotibiales",
    "name": "Curl Femoral Sentado",
    "muscle": "ISQUIOTIBIALES",
    "icon": "🎋",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Curl Femoral Sentado.png",
    "isLocked": false,
    "variants": [
      {
        "id": "curl_femoral_sentado",
        "label": "Curl Femoral Sentado",
        "seedName": "Curl Femoral Sentado",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Curl Femoral Sentado.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_femoral_tumbado_isquiotibiales",
    "name": "Curl Femoral Tumbado",
    "muscle": "ISQUIOTIBIALES",
    "icon": "🎋",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Curl Femoral Tumbado.png",
    "isLocked": false,
    "variants": [
      {
        "id": "curl_femoral_tumbado",
        "label": "Curl Femoral Tumbado",
        "seedName": "Curl Femoral Tumbado",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Curl Femoral Tumbado.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "peso_muerto_isquiotibiales",
    "name": "Peso Muerto",
    "muscle": "ISQUIOTIBIALES",
    "icon": "🎋",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Convencional.png",
    "isLocked": false,
    "variants": [
      {
        "id": "convencional",
        "label": "Convencional",
        "seedName": "Peso Muerto (Convencional)",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Convencional.png",
        "isLocked": false
      },
      {
        "id": "hexagonal",
        "label": "Hexagonal",
        "seedName": "Peso Muerto (Hexagonal)",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Hexagonal.png",
        "isLocked": false
      },
      {
        "id": "sumo",
        "label": "Sumo",
        "seedName": "Peso Muerto (Sumo)",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Sumo.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "cruce_de_poleas_pecho",
    "name": "Cruce de Poleas",
    "muscle": "PECHO",
    "icon": "🏋️‍♂️",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/pecho/Cruce de Poleas/Polea Alta.png",
    "isLocked": false,
    "variants": [
      {
        "id": "polea_alta",
        "label": "Polea Alta",
        "seedName": "Cruce de Poleas (Polea Alta)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Cruce de Poleas/Polea Alta.png",
        "isLocked": false
      },
      {
        "id": "polea_baja",
        "label": "Polea Baja",
        "seedName": "Cruce de Poleas (Polea Baja)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Cruce de Poleas/Polea Baja.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "fondos_pecho",
    "name": "Fondos",
    "muscle": "PECHO",
    "icon": "🏋️‍♂️",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos/Asistido Máquina.png",
    "isLocked": false,
    "variants": [
      {
        "id": "asistido_maquina",
        "label": "Asistido Máquina",
        "seedName": "Fondos (Asistido Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos/Asistido Máquina.png",
        "isLocked": false
      },
      {
        "id": "libre",
        "label": "Libre",
        "seedName": "Fondos (Libre)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos/Libre.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "peck_deck_mariposa_pecho",
    "name": "Peck Deck Mariposa",
    "muscle": "PECHO",
    "icon": "🏋️‍♂️",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/pecho/Peck Deck Mariposa.png",
    "isLocked": false,
    "variants": [
      {
        "id": "peck_deck_mariposa",
        "label": "Peck Deck Mariposa",
        "seedName": "Peck Deck Mariposa",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Peck Deck Mariposa.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "press_declinado_pecho",
    "name": "Press Declinado",
    "muscle": "PECHO",
    "icon": "🏋️‍♂️",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/pecho/Press Declinado/Barra.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra",
        "label": "Barra",
        "seedName": "Press Declinado (Barra)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Declinado/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Press Declinado (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Declinado/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "label": "Máquina",
        "seedName": "Press Declinado (Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Declinado/Máquina.png",
        "isLocked": false
      },
      {
        "id": "polea_cable",
        "label": "Polea Cable",
        "seedName": "Press Declinado (Polea Cable)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Declinado/Polea Cable.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "press_inclinado_pecho",
    "name": "Press Inclinado",
    "muscle": "PECHO",
    "icon": "🏋️‍♂️",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/pecho/Press Inclinado/Barra.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra",
        "label": "Barra",
        "seedName": "Press Inclinado (Barra)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Inclinado/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Press Inclinado (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Inclinado/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "label": "Máquina",
        "seedName": "Press Inclinado (Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Inclinado/Máquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "label": "Smith",
        "seedName": "Press Inclinado (Smith)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Inclinado/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "press_plano_pecho",
    "name": "Press Plano",
    "muscle": "PECHO",
    "icon": "🏋️‍♂️",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/pecho/Press Plano/Barra.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra",
        "label": "Barra",
        "seedName": "Press Plano (Barra)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Plano/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Press Plano (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Plano/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "label": "Máquina",
        "seedName": "Press Plano (Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Plano/Máquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "label": "Smith",
        "seedName": "Press Plano (Smith)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Plano/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "extensiones_cuadriceps_pierna",
    "name": "Extensiones Cuádriceps",
    "muscle": "CUÁDRICEPS",
    "icon": "🍑",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Extensiones Cuádriceps.png",
    "isLocked": false,
    "variants": [
      {
        "id": "extensiones_cuadriceps",
        "label": "Extensiones Cuádriceps",
        "seedName": "Extensiones Cuádriceps",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Extensiones Cuádriceps.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "prensa_piernas_45_pierna",
    "name": "Prensa Piernas 45",
    "muscle": "CUÁDRICEPS",
    "icon": "🍑",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Prensa Piernas 45.png",
    "isLocked": false,
    "variants": [
      {
        "id": "prensa_piernas_45",
        "label": "Prensa Piernas 45",
        "seedName": "Prensa Piernas 45",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Prensa Piernas 45.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "sentadilla_pierna",
    "name": "Sentadilla",
    "muscle": "CUÁDRICEPS",
    "icon": "🍑",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Barra Trasera.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra_trasera",
        "label": "Barra Trasera",
        "seedName": "Sentadilla (Barra Trasera)",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Barra Trasera.png",
        "isLocked": false
      },
      {
        "id": "frontal",
        "label": "Frontal",
        "seedName": "Sentadilla (Frontal)",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Frontal.png",
        "isLocked": false
      },
      {
        "id": "hack_maquina",
        "label": "Hack Máquina",
        "seedName": "Sentadilla (Hack Máquina)",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Hack Máquina.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "zancadas_pierna",
    "name": "Zancadas",
    "muscle": "CUÁDRICEPS",
    "icon": "🍑",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Barra.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra",
        "label": "Barra",
        "seedName": "Zancadas (Barra)",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Barra.png",
        "isLocked": false
      },
      {
        "id": "bulgara",
        "label": "Búlgara",
        "seedName": "Zancadas (Búlgara)",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Búlgara.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Zancadas (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "label": "Smith",
        "seedName": "Zancadas (Smith)",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "encogimientos_trapecios",
    "name": "Encogimientos",
    "muscle": "ESPALDA",
    "icon": "🚣",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Trapecios/Encogimientos/Barra.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra",
        "label": "Barra",
        "seedName": "Encogimientos (Barra)",
        "imagePath": "/ejercicioimg/ejercicios/Trapecios/Encogimientos/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Encogimientos (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/Trapecios/Encogimientos/Mancuernas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "copa_triceps",
    "name": "Copa",
    "muscle": "TRÍCEPS",
    "icon": "🏇",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Copa/Dos Manos.png",
    "isLocked": false,
    "variants": [
      {
        "id": "dos_manos",
        "label": "Dos Manos",
        "seedName": "Copa (Dos Manos)",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Copa/Dos Manos.png",
        "isLocked": false
      },
      {
        "id": "una_mano",
        "label": "Una Mano",
        "seedName": "Copa (Una Mano)",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Copa/Una Mano.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "extensiones_en_polea_triceps",
    "name": "Extensiones en Polea",
    "muscle": "TRÍCEPS",
    "icon": "🏇",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Extensiones en Polea/Cuerda.png",
    "isLocked": false,
    "variants": [
      {
        "id": "cuerda",
        "label": "Cuerda",
        "seedName": "Extensiones en Polea (Cuerda)",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Extensiones en Polea/Cuerda.png",
        "isLocked": false
      },
      {
        "id": "una_mano",
        "label": "Una Mano",
        "seedName": "Extensiones en Polea (Una Mano)",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Extensiones en Polea/Una Mano.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "fondos_triceps",
    "name": "Fondos",
    "muscle": "TRÍCEPS",
    "icon": "🏇",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Bancos.png",
    "isLocked": false,
    "variants": [
      {
        "id": "bancos",
        "label": "Bancos",
        "seedName": "Fondos (Bancos)",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Bancos.png",
        "isLocked": false
      },
      {
        "id": "paralelas",
        "label": "Paralelas",
        "seedName": "Fondos (Paralelas)",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Paralelas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "patada_de_triceps_triceps",
    "name": "Patada de Tríceps",
    "muscle": "TRÍCEPS",
    "icon": "🏇",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Patada de Tríceps.png",
    "isLocked": false,
    "variants": [
      {
        "id": "patada_de_triceps",
        "label": "Patada de Tríceps",
        "seedName": "Patada de Tríceps",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Patada de Tríceps.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "press_frances_triceps",
    "name": "Press Francés",
    "muscle": "TRÍCEPS",
    "icon": "🏇",
    "metrics": {
      "weight": true,
      "reps": true,
      "time": false,
      "distance": false,
      "rpe": false
    },
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Press Francés/Barra Z Acostado.png",
    "isLocked": false,
    "variants": [
      {
        "id": "barra_z_acostado",
        "label": "Barra Z Acostado",
        "seedName": "Press Francés (Barra Z Acostado)",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press Francés/Barra Z Acostado.png",
        "isLocked": false
      },
      {
        "id": "barra_z_sentado",
        "label": "Barra Z Sentado",
        "seedName": "Press Francés (Barra Z Sentado)",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press Francés/Barra Z Sentado.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "label": "Mancuernas",
        "seedName": "Press Francés (Mancuernas)",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press Francés/Mancuernas.png",
        "isLocked": false
      }
    ]
  }
];
