// AUTO-GENERATED by scripts/generateCatalog.mjs — DO NOT EDIT MANUALLY
// Run "npm run catalog" to regenerate after moving images.
// Generated: 2026-06-06T00:28:24.768Z

export interface ManifestVariant {
  id: string;
  name: string;
  imagePath: string;
  isLocked: boolean;
}

export interface ManifestExercise {
  id: string;
  name: string;
  muscle: string;
  folderName: string;
  imagePath: string;
  isLocked: boolean;
  variantGroup: string | null;
  variants: ManifestVariant[];
}

export const IMAGE_MANIFEST: ManifestExercise[] = [
  {
    "id": "crunch_abdomen",
    "name": "Crunch",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Estandar.png",
    "isLocked": false,
    "variantGroup": "Crunch",
    "variants": [
      {
        "id": "estandar",
        "name": "Estandar",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Estandar.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Maquina.png",
        "isLocked": false
      },
      {
        "id": "polea_alta",
        "name": "Polea Alta",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Polea Alta.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "crunch_oblicuo_abdomen",
    "name": "Crunch oblicuo",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch oblicuo/Crunch oblicuo.png",
    "isLocked": false,
    "variantGroup": "Crunch oblicuo",
    "variants": [
      {
        "id": "crunch_oblicuo",
        "name": "Crunch oblicuo",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch oblicuo/Crunch oblicuo.png",
        "isLocked": false
      },
      {
        "id": "encogimientos_rodillas",
        "name": "Encogimientos Rodillas",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch oblicuo/Encogimientos Rodillas.png",
        "isLocked": false
      },
      {
        "id": "gemini_generated_image_2mgqe52mgqe52mgq",
        "name": "Gemini_Generated_Image_2mgqe52mgqe52mgq",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch oblicuo/Gemini_Generated_Image_2mgqe52mgqe52mgq-Photoroom.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevacion_piernas_colgado",
    "name": "Elevacion Piernas Colgado",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Elevacion Piernas Colgado.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "inversos_abdomen",
    "name": "Inversos",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Inversos/Encogimientos de rodillas para abdominales.png",
    "isLocked": false,
    "variantGroup": "Inversos",
    "variants": [
      {
        "id": "encogimientos_de_rodillas_para_abdominales",
        "name": "Encogimientos de rodillas para abdominales",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Inversos/Encogimientos de rodillas para abdominales.png",
        "isLocked": false
      },
      {
        "id": "inversos",
        "name": "Inversos",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Inversos/Inversos.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "plancha_abdomen",
    "name": "plancha",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/plancha/Con Flexion.png",
    "isLocked": false,
    "variantGroup": "plancha",
    "variants": [
      {
        "id": "con_flexion",
        "name": "Con Flexion",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/plancha/Con Flexion.png",
        "isLocked": false
      },
      {
        "id": "estatica",
        "name": "Estatica",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/plancha/Estatica.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "russian_twist",
    "name": "Russian Twist",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Russian Twist.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_muneca_barra",
    "name": "Curl Muneca Barra",
    "muscle": "ANTEBRAZO",
    "folderName": "Antebrazo",
    "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Curl Muneca Barra.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "pronacion_antebrazo",
    "name": "Pronacion",
    "muscle": "ANTEBRAZO",
    "folderName": "Antebrazo",
    "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Pronacion/Extension Muneca.png",
    "isLocked": false,
    "variantGroup": "Pronacion",
    "variants": [
      {
        "id": "extension_muneca",
        "name": "Extension Muneca",
        "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Pronacion/Extension Muneca.png",
        "isLocked": false
      },
      {
        "id": "invertido",
        "name": "Invertido",
        "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Pronacion/Invertido.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_biceps_bayoneta",
    "name": "Curl Biceps Bayoneta",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Biceps Bayoneta.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_spider",
    "name": "Curl Spider",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Spider.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_normal_biceps",
    "name": "Curl Normal",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlNormal/Barra.png",
    "isLocked": false,
    "variantGroup": "CurlNormal",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlNormal/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlNormal/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "polea_alta",
        "name": "Polea Alta",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlNormal/Polea Alta.png",
        "isLocked": false
      },
      {
        "id": "polea_baja",
        "name": "Polea Baja",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlNormal/Polea Baja.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "martillo_biceps",
    "name": "Martillo",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Cuerda.png",
    "isLocked": false,
    "variantGroup": "Martillo",
    "variants": [
      {
        "id": "cuerda",
        "name": "Cuerda",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Cuerda.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Mancuernas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "predicador_biceps",
    "name": "Predicador",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/Barra.png",
    "isLocked": false,
    "variantGroup": "Predicador",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/Barra.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/Maquina.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "caminadoras_cardio",
    "name": "Caminadoras",
    "muscle": "CARDIO",
    "folderName": "Cardio",
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Bicicleta.png",
    "isLocked": false,
    "variantGroup": "Caminadoras",
    "variants": [
      {
        "id": "bicicleta",
        "name": "Bicicleta",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Bicicleta.png",
        "isLocked": false
      },
      {
        "id": "cinta",
        "name": "Cinta",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Cinta.png",
        "isLocked": false
      },
      {
        "id": "eliptica",
        "name": "Eliptica",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Eliptica.png",
        "isLocked": false
      },
      {
        "id": "escaladora",
        "name": "Escaladora",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Escaladora.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "cardio_saltar_cuerda",
    "name": "Cardio Saltar Cuerda",
    "muscle": "CARDIO",
    "folderName": "Cardio",
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Cardio Saltar Cuerda.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "remo_concept2",
    "name": "Remo Concept2",
    "muscle": "CARDIO",
    "folderName": "Cardio",
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Remo Concept2.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "saltar_cuerda",
    "name": "Saltar Cuerda",
    "muscle": "CARDIO",
    "folderName": "Cardio",
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Saltar Cuerda.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "arnes_cuello",
    "name": "Arnes Cuello",
    "muscle": "CUELLO",
    "folderName": "Cuello",
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Arnes Cuello.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "extension_disco",
    "name": "Extension Disco",
    "muscle": "CUELLO",
    "folderName": "Cuello",
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Extension Disco.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "flexion_disco",
    "name": "Flexion Disco",
    "muscle": "CUELLO",
    "folderName": "Cuello",
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Flexion Disco.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "dominadas_espalda",
    "name": "Dominadas",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Asistida.png",
    "isLocked": false,
    "variantGroup": "Dominadas",
    "variants": [
      {
        "id": "asistida",
        "name": "Asistida",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Asistida.png",
        "isLocked": false
      },
      {
        "id": "libre",
        "name": "Libre",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Libre.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "jalon_espalda",
    "name": "Jalon",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalon/Agarre Estrecho.png",
    "isLocked": false,
    "variantGroup": "Jalon",
    "variants": [
      {
        "id": "agarre_estrecho",
        "name": "Agarre Estrecho",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalon/Agarre Estrecho.png",
        "isLocked": false
      },
      {
        "id": "polea_alta",
        "name": "Polea Alta",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalon/Polea Alta.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "pull_over_polea",
    "name": "Pull Over Polea",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Pull Over Polea.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "remo_espalda",
    "name": "Remo",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo/Barra Pendlay.png",
    "isLocked": false,
    "variantGroup": "Remo",
    "variants": [
      {
        "id": "barra_pendlay",
        "name": "Barra Pendlay",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo/Barra Pendlay.png",
        "isLocked": false
      },
      {
        "id": "barra_yates",
        "name": "Barra Yates",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo/Barra Yates.png",
        "isLocked": false
      },
      {
        "id": "mancuerna",
        "name": "Mancuerna",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo/Mancuerna.png",
        "isLocked": false
      },
      {
        "id": "t_barra",
        "name": "T-Barra",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo/T-Barra.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "remo_sentado_espalda",
    "name": "Remo sentado",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo sentado/Gironda.png",
    "isLocked": false,
    "variantGroup": "Remo sentado",
    "variants": [
      {
        "id": "gironda",
        "name": "Gironda",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo sentado/Gironda.png",
        "isLocked": false
      },
      {
        "id": "pecho_apoyado",
        "name": "Pecho Apoyado",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo sentado/Pecho Apoyado.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "gemelos_sentado",
    "name": "Gemelos Sentado",
    "muscle": "PANTORRILLAS",
    "folderName": "Gemelos",
    "imagePath": "/ejercicioimg/ejercicios/Gemelos/Gemelos Sentado.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "parado_gemelos",
    "name": "Parado",
    "muscle": "PANTORRILLAS",
    "folderName": "Gemelos",
    "imagePath": "/ejercicioimg/ejercicios/Gemelos/Parado/Maquina.png",
    "isLocked": false,
    "variantGroup": "Parado",
    "variants": [
      {
        "id": "maquina",
        "name": "Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Gemelos/Parado/Maquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/Gemelos/Parado/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "abduccion_maquina",
    "name": "Abduccion Maquina",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Abduccion Maquina.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "caminata_de_pato",
    "name": "Caminata de Pato",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Caminata de Pato.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "columpios_kettlebell",
    "name": "Columpios Kettlebell",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Columpios Kettlebell.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "hip_trust_gluteo",
    "name": "Hip Trust",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/HipTrust/Barra.png",
    "isLocked": false,
    "variantGroup": "HipTrust",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/HipTrust/Barra.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/HipTrust/Maquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/HipTrust/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "patada_gluteo",
    "name": "Patada",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada/Maquina.png",
    "isLocked": false,
    "variantGroup": "Patada",
    "variants": [
      {
        "id": "maquina",
        "name": "Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada/Maquina.png",
        "isLocked": false
      },
      {
        "id": "polea",
        "name": "Polea",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada/Polea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "rana_frog_pump",
    "name": "Rana Frog Pump",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Rana Frog Pump.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "step_up_mancuernas",
    "name": "Step Up Mancuernas",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Step Up Mancuernas.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "elevacion_frontal_hombro",
    "name": "Elevacion frontal",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevacion frontal/Disco Dos Manos.png",
    "isLocked": false,
    "variantGroup": "Elevacion frontal",
    "variants": [
      {
        "id": "disco_dos_manos",
        "name": "Disco Dos Manos",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevacion frontal/Disco Dos Manos.png",
        "isLocked": false
      },
      {
        "id": "mancuerna_dos_manos",
        "name": "Mancuerna Dos Manos",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevacion frontal/Mancuerna Dos Manos.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevacion frontal/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "polea",
        "name": "Polea",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevacion frontal/Polea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevacion_lateral_hombro",
    "name": "elevacion lateral",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/elevacion lateral/Mancuernas.png",
    "isLocked": false,
    "variantGroup": "elevacion lateral",
    "variants": [
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/elevacion lateral/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/elevacion lateral/Maquina.png",
        "isLocked": false
      },
      {
        "id": "polea",
        "name": "Polea",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/elevacion lateral/Polea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "face_pull",
    "name": "Face Pull",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Face Pull.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "militar_hombro",
    "name": "Militar",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Militar/Barra.png",
    "isLocked": false,
    "variantGroup": "Militar",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Militar/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Militar/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Militar/Maquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Militar/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "pajaros_vuelos_mancuernas",
    "name": "Pajaros Vuelos Mancuernas",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Pajaros Vuelos Mancuernas.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "peck_deck_invertido",
    "name": "Peck Deck Invertido",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Peck Deck Invertido.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_femoral_sentado",
    "name": "Curl Femoral Sentado",
    "muscle": "ISQUIOTIBIALES",
    "folderName": "Isquiotibiales",
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Curl Femoral Sentado.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_femoral_tumbado",
    "name": "Curl Femoral Tumbado",
    "muscle": "ISQUIOTIBIALES",
    "folderName": "Isquiotibiales",
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Curl Femoral Tumbado.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "peso_muerto_isquiotibiales",
    "name": "Peso Muerto",
    "muscle": "ISQUIOTIBIALES",
    "folderName": "Isquiotibiales",
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Convencional.png",
    "isLocked": false,
    "variantGroup": "Peso Muerto",
    "variants": [
      {
        "id": "convencional",
        "name": "Convencional",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Convencional.png",
        "isLocked": false
      },
      {
        "id": "hexagonal",
        "name": "Hexagonal",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Hexagonal.png",
        "isLocked": false
      },
      {
        "id": "sumo",
        "name": "Sumo",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Sumo.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "crude_de_polea_pecho",
    "name": "Crude de polea",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Crude de polea/Polea Alta.png",
    "isLocked": false,
    "variantGroup": "Crude de polea",
    "variants": [
      {
        "id": "polea_alta",
        "name": "Polea Alta",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Crude de polea/Polea Alta.png",
        "isLocked": false
      },
      {
        "id": "polea_baja",
        "name": "Polea Baja",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Crude de polea/Polea Baja.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "declinado_pecho",
    "name": "Declinado",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Declinado/Barra.png",
    "isLocked": false,
    "variantGroup": "Declinado",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Declinado/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Declinado/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "polea_cable",
        "name": "Polea Cable",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Declinado/Polea Cable.png",
        "isLocked": false
      },
      {
        "id": "press_declinado_en_maquina",
        "name": "Press Declinado En Maquina",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Declinado/PressDeclinadoEnMaquina.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "fondos_pecho_pecho",
    "name": "Fondos pecho",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos pecho/Asistido Maquina.png",
    "isLocked": false,
    "variantGroup": "Fondos pecho",
    "variants": [
      {
        "id": "asistido_maquina",
        "name": "Asistido Maquina",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos pecho/Asistido Maquina.png",
        "isLocked": false
      },
      {
        "id": "libre",
        "name": "Libre",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos pecho/Libre.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "inclinado_pecho",
    "name": "Inclinado",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Inclinado/Barra.png",
    "isLocked": false,
    "variantGroup": "Inclinado",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Inclinado/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Inclinado/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Maquina",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Inclinado/Maquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Inclinado/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "peck_deck_mariposa",
    "name": "Peck Deck Mariposa",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Peck Deck Mariposa.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "plano_pecho",
    "name": "Plano",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Plano/Barra.png",
    "isLocked": false,
    "variantGroup": "Plano",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Plano/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Plano/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Maquina",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Plano/Maquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Plano/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "buenos_dias",
    "name": "Buenos Dias",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Buenos Dias.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "extensiones_cuadriceps",
    "name": "Extensiones Cuadriceps",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Extensiones Cuadriceps.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "prensa_piernas_45",
    "name": "Prensa Piernas 45",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Prensa Piernas 45.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "sentadilla_pierna",
    "name": "Sentadilla",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Barra Trasera.png",
    "isLocked": false,
    "variantGroup": "Sentadilla",
    "variants": [
      {
        "id": "barra_trasera",
        "name": "Barra Trasera",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Barra Trasera.png",
        "isLocked": false
      },
      {
        "id": "frontal",
        "name": "Frontal",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Frontal.png",
        "isLocked": false
      },
      {
        "id": "hack_maquina",
        "name": "Hack Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Hack Maquina.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "zancadas_pierna",
    "name": "Zancadas",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Barra.png",
    "isLocked": false,
    "variantGroup": "Zancadas",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Barra.png",
        "isLocked": false
      },
      {
        "id": "bulgara",
        "name": "Bulgara",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Bulgara.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "barra",
    "name": "Barra",
    "muscle": "ESPALDA",
    "folderName": "Trapecios",
    "imagePath": "/ejercicioimg/ejercicios/Trapecios/Barra.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "mancuernas",
    "name": "Mancuernas",
    "muscle": "ESPALDA",
    "folderName": "Trapecios",
    "imagePath": "/ejercicioimg/ejercicios/Trapecios/Mancuernas.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "copa_triceps",
    "name": "copa",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/copa/Dos Manos.png",
    "isLocked": false,
    "variantGroup": "copa",
    "variants": [
      {
        "id": "dos_manos",
        "name": "Dos Manos",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/copa/Dos Manos.png",
        "isLocked": false
      },
      {
        "id": "una_mano",
        "name": "Una Mano",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/copa/Una Mano.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "extension_tricep_triceps",
    "name": "Extension tricep",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Extension tricep/Cuerda.png",
    "isLocked": false,
    "variantGroup": "Extension tricep",
    "variants": [
      {
        "id": "cuerda",
        "name": "Cuerda",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Extension tricep/Cuerda.png",
        "isLocked": false
      },
      {
        "id": "una_mano",
        "name": "Una Mano",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Extension tricep/Una Mano.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "fondos_triceps",
    "name": "Fondos",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Bancos.png",
    "isLocked": false,
    "variantGroup": "Fondos",
    "variants": [
      {
        "id": "bancos",
        "name": "Bancos",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Bancos.png",
        "isLocked": false
      },
      {
        "id": "paralelas",
        "name": "Paralelas",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Paralelas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "patada_triceps_mancuerna",
    "name": "Patada Triceps Mancuerna",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Patada Triceps Mancuerna.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "press_frances_triceps",
    "name": "Press frances",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Press frances/Barra Z Acostado.png",
    "isLocked": false,
    "variantGroup": "Press frances",
    "variants": [
      {
        "id": "barra_z_acostado",
        "name": "Barra Z Acostado",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press frances/Barra Z Acostado.png",
        "isLocked": false
      },
      {
        "id": "barra_z_sentado",
        "name": "Barra Z Sentado",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press frances/Barra Z Sentado.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press frances/Mancuernas.png",
        "isLocked": false
      }
    ]
  }
];

/** All exercises that have variants (main card = base, arrows cycle variants) */
export const MANIFEST_WITH_VARIANTS = IMAGE_MANIFEST.filter(e => e.variants.length > 1);

/** Standalone exercises (single image, no variant cycling) */
export const MANIFEST_STANDALONE = IMAGE_MANIFEST.filter(e => e.variants.length <= 1);
