// AUTO-GENERATED by scripts/generateCatalog.mjs — DO NOT EDIT MANUALLY
// Run "npm run catalog" to regenerate after moving images.
// Generated: 2026-07-02T15:04:37.794Z

export interface ManifestVariant {
  id: string;
  name: string;
  imagePath: string;
  isLocked: boolean;
}

export interface ManifestExercise {
  id: string;
  name: string;
  muscle: string;
  folderName: string;
  imagePath: string;
  isLocked: boolean;
  variantGroup: string | null;
  variants: ManifestVariant[];
}

export const IMAGE_MANIFEST: ManifestExercise[] = [
  {
    "id": "crunch_abdomen",
    "name": "Crunch",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Estándar.png",
    "isLocked": false,
    "variantGroup": "Crunch",
    "variants": [
      {
        "id": "estandar",
        "name": "Estándar",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Estándar.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Máquina.png",
        "isLocked": false
      },
      {
        "id": "polea_alta",
        "name": "Polea Alta",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/Polea Alta.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "crunch_inverso_abdomen",
    "name": "Crunch Inverso",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Inverso/Encogimientos de Rodillas.png",
    "isLocked": false,
    "variantGroup": "Crunch Inverso",
    "variants": [
      {
        "id": "encogimientos_de_rodillas",
        "name": "Encogimientos de Rodillas",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Inverso/Encogimientos de Rodillas.png",
        "isLocked": false
      },
      {
        "id": "talones",
        "name": "Talones",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Inverso/Talones.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "crunch_oblicuo_abdomen",
    "name": "Crunch Oblicuo",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Oblicuo/Encogimientos de Rodillas.png",
    "isLocked": false,
    "variantGroup": "Crunch Oblicuo",
    "variants": [
      {
        "id": "encogimientos_de_rodillas",
        "name": "Encogimientos de Rodillas",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Oblicuo/Encogimientos de Rodillas.png",
        "isLocked": false
      },
      {
        "id": "estandar",
        "name": "Estándar",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Oblicuo/Estándar.png",
        "isLocked": false
      },
      {
        "id": "gemini_generated_image_2mgqe52mgqe52mgq",
        "name": "Gemini_Generated_Image_2mgqe52mgqe52mgq",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch Oblicuo/ocultos/Gemini_Generated_Image_2mgqe52mgqe52mgq-Photoroom.png",
        "isLocked": true
      }
    ]
  },
  {
    "id": "elevacion_de_piernas",
    "name": "Elevación de Piernas",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Elevación de Piernas.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "plancha_abdomen",
    "name": "Plancha",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Plancha/Con Flexión.png",
    "isLocked": false,
    "variantGroup": "Plancha",
    "variants": [
      {
        "id": "con_flexion",
        "name": "Con Flexión",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Plancha/Con Flexión.png",
        "isLocked": false
      },
      {
        "id": "estatica",
        "name": "Estática",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Plancha/Estática.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "russian_twist",
    "name": "Russian Twist",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Russian Twist.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_de_muneca",
    "name": "Curl de Muñeca",
    "muscle": "ANTEBRAZO",
    "folderName": "Antebrazo",
    "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Curl de Muñeca.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "extension_de_muneca_antebrazo",
    "name": "Extensión de Muñeca",
    "muscle": "ANTEBRAZO",
    "folderName": "Antebrazo",
    "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Extensión de Muñeca/Invertido.png",
    "isLocked": false,
    "variantGroup": "Extensión de Muñeca",
    "variants": [
      {
        "id": "invertido",
        "name": "Invertido",
        "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Extensión de Muñeca/Invertido.png",
        "isLocked": false
      },
      {
        "id": "supino",
        "name": "Supino",
        "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Extensión de Muñeca/Supino.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_bayoneta",
    "name": "Curl Bayoneta",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Bayoneta.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_normal_biceps",
    "name": "Curl Normal",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Normal/Barra.png",
    "isLocked": false,
    "variantGroup": "Curl Normal",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Normal/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Normal/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "polea_alta",
        "name": "Polea Alta",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Normal/Polea Alta.png",
        "isLocked": false
      },
      {
        "id": "polea_baja",
        "name": "Polea Baja",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Normal/Polea Baja.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_spider",
    "name": "Curl Spider",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Curl Spider.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "martillo_biceps",
    "name": "Martillo",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Cuerda.png",
    "isLocked": false,
    "variantGroup": "Martillo",
    "variants": [
      {
        "id": "cuerda",
        "name": "Cuerda",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Cuerda.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Mancuernas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "predicador_biceps",
    "name": "Predicador",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/Barra.png",
    "isLocked": false,
    "variantGroup": "Predicador",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/Barra.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/Máquina.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "caminadoras_cardio",
    "name": "Caminadoras",
    "muscle": "CARDIO",
    "folderName": "Cardio",
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Bicicleta.png",
    "isLocked": false,
    "variantGroup": "Caminadoras",
    "variants": [
      {
        "id": "bicicleta",
        "name": "Bicicleta",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Bicicleta.png",
        "isLocked": false
      },
      {
        "id": "cinta",
        "name": "Cinta",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Cinta.png",
        "isLocked": false
      },
      {
        "id": "eliptica",
        "name": "Elíptica",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Elíptica.png",
        "isLocked": false
      },
      {
        "id": "escaladora",
        "name": "Escaladora",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/Escaladora.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "remo",
    "name": "Remo",
    "muscle": "CARDIO",
    "folderName": "Cardio",
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Remo.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "salto_a_la_cuerda",
    "name": "Salto a la Cuerda",
    "muscle": "CARDIO",
    "folderName": "Cardio",
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Salto a la Cuerda.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "arnes_de_cuello",
    "name": "Arnés de Cuello",
    "muscle": "CUELLO",
    "folderName": "Cuello",
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Arnés de Cuello.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "extension_con_disco",
    "name": "Extensión con Disco",
    "muscle": "CUELLO",
    "folderName": "Cuello",
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Extensión con Disco.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "flexion_con_disco",
    "name": "Flexión con Disco",
    "muscle": "CUELLO",
    "folderName": "Cuello",
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Flexión con Disco.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "dominadas_espalda",
    "name": "Dominadas",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Asistida.png",
    "isLocked": false,
    "variantGroup": "Dominadas",
    "variants": [
      {
        "id": "asistida",
        "name": "Asistida",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Asistida.png",
        "isLocked": false
      },
      {
        "id": "libre",
        "name": "Libre",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Libre.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "jalon_espalda",
    "name": "Jalón",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalón/Agarre Estrecho.png",
    "isLocked": false,
    "variantGroup": "Jalón",
    "variants": [
      {
        "id": "agarre_estrecho",
        "name": "Agarre Estrecho",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalón/Agarre Estrecho.png",
        "isLocked": false
      },
      {
        "id": "polea_alta",
        "name": "Polea Alta",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalón/Polea Alta.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "pull_over_polea",
    "name": "Pull Over Polea",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Pull Over Polea.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "remo_con_barra_espalda",
    "name": "Remo con Barra",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo con Barra/Barra Pendlay.png",
    "isLocked": false,
    "variantGroup": "Remo con Barra",
    "variants": [
      {
        "id": "barra_pendlay",
        "name": "Barra Pendlay",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo con Barra/Barra Pendlay.png",
        "isLocked": false
      },
      {
        "id": "barra_yates",
        "name": "Barra Yates",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo con Barra/Barra Yates.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo con Barra/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "t_barra",
        "name": "T-Barra",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo con Barra/T-Barra.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "remo_sentado_espalda",
    "name": "Remo Sentado",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo Sentado/Gironda.png",
    "isLocked": false,
    "variantGroup": "Remo Sentado",
    "variants": [
      {
        "id": "gironda",
        "name": "Gironda",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo Sentado/Gironda.png",
        "isLocked": false
      },
      {
        "id": "pecho_apoyado",
        "name": "Pecho Apoyado",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo Sentado/Pecho Apoyado.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevacion_de_pie_gemelos",
    "name": "Elevación de Pie",
    "muscle": "PANTORRILLAS",
    "folderName": "Gemelos",
    "imagePath": "/ejercicioimg/ejercicios/Gemelos/Elevación de Pie/Máquina.png",
    "isLocked": false,
    "variantGroup": "Elevación de Pie",
    "variants": [
      {
        "id": "maquina",
        "name": "Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Gemelos/Elevación de Pie/Máquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/Gemelos/Elevación de Pie/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevacion_sentado",
    "name": "Elevación Sentado",
    "muscle": "PANTORRILLAS",
    "folderName": "Gemelos",
    "imagePath": "/ejercicioimg/ejercicios/Gemelos/Elevación Sentado.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "abduccion_de_cadera",
    "name": "Abducción de Cadera",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Abducción de Cadera.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "caminata_de_pato",
    "name": "Caminata de Pato",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Caminata de Pato.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "columpios_kettlebell",
    "name": "Columpios Kettlebell",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Columpios Kettlebell.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "elevacion_de_rana",
    "name": "Elevación de Rana",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Elevación de Rana.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "hip_thrust_gluteo",
    "name": "Hip Thrust",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Hip Thrust/Barra.png",
    "isLocked": false,
    "variantGroup": "Hip Thrust",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Hip Thrust/Barra.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Hip Thrust/Máquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Hip Thrust/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "patada_de_gluteo_gluteo",
    "name": "Patada de Glúteo",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada de Glúteo/Máquina.png",
    "isLocked": false,
    "variantGroup": "Patada de Glúteo",
    "variants": [
      {
        "id": "maquina",
        "name": "Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada de Glúteo/Máquina.png",
        "isLocked": false
      },
      {
        "id": "polea",
        "name": "Polea",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada de Glúteo/Polea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "step_up",
    "name": "Step Up",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Step Up.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "elevaciones_frontales_hombro",
    "name": "Elevaciones Frontales",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Frontales/Disco Dos Manos.png",
    "isLocked": false,
    "variantGroup": "Elevaciones Frontales",
    "variants": [
      {
        "id": "disco_dos_manos",
        "name": "Disco Dos Manos",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Frontales/Disco Dos Manos.png",
        "isLocked": false
      },
      {
        "id": "mancuerna_dos_manos",
        "name": "Mancuerna Dos Manos",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Frontales/Mancuerna Dos Manos.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Frontales/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "polea",
        "name": "Polea",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Frontales/Polea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevaciones_laterales_hombro",
    "name": "Elevaciones Laterales",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Laterales/Mancuernas.png",
    "isLocked": false,
    "variantGroup": "Elevaciones Laterales",
    "variants": [
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Laterales/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Laterales/Máquina.png",
        "isLocked": false
      },
      {
        "id": "polea",
        "name": "Polea",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevaciones Laterales/Polea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "face_pull",
    "name": "Face Pull",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Face Pull.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "peck_deck_invertido",
    "name": "Peck Deck Invertido",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Peck Deck Invertido.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "press_militar_hombro",
    "name": "Press Militar",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Press Militar/Barra.png",
    "isLocked": false,
    "variantGroup": "Press Militar",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Press Militar/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Press Militar/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Press Militar/Máquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Press Militar/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "pajaros_vuelos_posterior",
    "name": "Pájaros Vuelos Posterior",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Pájaros Vuelos Posterior.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "buenos_dias",
    "name": "Buenos Días",
    "muscle": "ISQUIOTIBIALES",
    "folderName": "Isquiotibiales",
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Buenos Días.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_femoral_sentado",
    "name": "Curl Femoral Sentado",
    "muscle": "ISQUIOTIBIALES",
    "folderName": "Isquiotibiales",
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Curl Femoral Sentado.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_femoral_tumbado",
    "name": "Curl Femoral Tumbado",
    "muscle": "ISQUIOTIBIALES",
    "folderName": "Isquiotibiales",
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Curl Femoral Tumbado.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "peso_muerto_isquiotibiales",
    "name": "Peso Muerto",
    "muscle": "ISQUIOTIBIALES",
    "folderName": "Isquiotibiales",
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Convencional.png",
    "isLocked": false,
    "variantGroup": "Peso Muerto",
    "variants": [
      {
        "id": "convencional",
        "name": "Convencional",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Convencional.png",
        "isLocked": false
      },
      {
        "id": "hexagonal",
        "name": "Hexagonal",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Hexagonal.png",
        "isLocked": false
      },
      {
        "id": "sumo",
        "name": "Sumo",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Sumo.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "cruce_de_poleas_pecho",
    "name": "Cruce de Poleas",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Cruce de Poleas/Polea Alta.png",
    "isLocked": false,
    "variantGroup": "Cruce de Poleas",
    "variants": [
      {
        "id": "polea_alta",
        "name": "Polea Alta",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Cruce de Poleas/Polea Alta.png",
        "isLocked": false
      },
      {
        "id": "polea_baja",
        "name": "Polea Baja",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Cruce de Poleas/Polea Baja.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "fondos_pecho",
    "name": "Fondos",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos/Asistido Máquina.png",
    "isLocked": false,
    "variantGroup": "Fondos",
    "variants": [
      {
        "id": "asistido_maquina",
        "name": "Asistido Máquina",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos/Asistido Máquina.png",
        "isLocked": false
      },
      {
        "id": "libre",
        "name": "Libre",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos/Libre.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "peck_deck_mariposa",
    "name": "Peck Deck Mariposa",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Peck Deck Mariposa.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "press_declinado_pecho",
    "name": "Press Declinado",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Press Declinado/Barra.png",
    "isLocked": false,
    "variantGroup": "Press Declinado",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Declinado/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Declinado/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Máquina",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Declinado/Máquina.png",
        "isLocked": false
      },
      {
        "id": "polea_cable",
        "name": "Polea Cable",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Declinado/Polea Cable.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "press_inclinado_pecho",
    "name": "Press Inclinado",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Press Inclinado/Barra.png",
    "isLocked": false,
    "variantGroup": "Press Inclinado",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Inclinado/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Inclinado/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Máquina",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Inclinado/Máquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Inclinado/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "press_plano_pecho",
    "name": "Press Plano",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Press Plano/Barra.png",
    "isLocked": false,
    "variantGroup": "Press Plano",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Plano/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Plano/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "maquina",
        "name": "Máquina",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Plano/Máquina.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Press Plano/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "extensiones_cuadriceps",
    "name": "Extensiones Cuádriceps",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Extensiones Cuádriceps.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "prensa_piernas_45",
    "name": "Prensa Piernas 45",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Prensa Piernas 45.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "sentadilla_pierna",
    "name": "Sentadilla",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Barra Trasera.png",
    "isLocked": false,
    "variantGroup": "Sentadilla",
    "variants": [
      {
        "id": "barra_trasera",
        "name": "Barra Trasera",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Barra Trasera.png",
        "isLocked": false
      },
      {
        "id": "frontal",
        "name": "Frontal",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Frontal.png",
        "isLocked": false
      },
      {
        "id": "hack_maquina",
        "name": "Hack Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Hack Máquina.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "zancadas_pierna",
    "name": "Zancadas",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Barra.png",
    "isLocked": false,
    "variantGroup": "Zancadas",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Barra.png",
        "isLocked": false
      },
      {
        "id": "bulgara",
        "name": "Búlgara",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Búlgara.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "smith",
        "name": "Smith",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Smith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "encogimientos_trapecios",
    "name": "Encogimientos",
    "muscle": "ESPALDA",
    "folderName": "Trapecios",
    "imagePath": "/ejercicioimg/ejercicios/Trapecios/Encogimientos/Barra.png",
    "isLocked": false,
    "variantGroup": "Encogimientos",
    "variants": [
      {
        "id": "barra",
        "name": "Barra",
        "imagePath": "/ejercicioimg/ejercicios/Trapecios/Encogimientos/Barra.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Trapecios/Encogimientos/Mancuernas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "copa_triceps",
    "name": "Copa",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Copa/Dos Manos.png",
    "isLocked": false,
    "variantGroup": "Copa",
    "variants": [
      {
        "id": "dos_manos",
        "name": "Dos Manos",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Copa/Dos Manos.png",
        "isLocked": false
      },
      {
        "id": "una_mano",
        "name": "Una Mano",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Copa/Una Mano.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "extensiones_en_polea_triceps",
    "name": "Extensiones en Polea",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Extensiones en Polea/Cuerda.png",
    "isLocked": false,
    "variantGroup": "Extensiones en Polea",
    "variants": [
      {
        "id": "cuerda",
        "name": "Cuerda",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Extensiones en Polea/Cuerda.png",
        "isLocked": false
      },
      {
        "id": "una_mano",
        "name": "Una Mano",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Extensiones en Polea/Una Mano.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "fondos_triceps",
    "name": "Fondos",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Bancos.png",
    "isLocked": false,
    "variantGroup": "Fondos",
    "variants": [
      {
        "id": "bancos",
        "name": "Bancos",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Bancos.png",
        "isLocked": false
      },
      {
        "id": "paralelas",
        "name": "Paralelas",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Paralelas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "patada_de_triceps",
    "name": "Patada de Tríceps",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Patada de Tríceps.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "press_frances_triceps",
    "name": "Press Francés",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Press Francés/Barra Z Acostado.png",
    "isLocked": false,
    "variantGroup": "Press Francés",
    "variants": [
      {
        "id": "barra_z_acostado",
        "name": "Barra Z Acostado",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press Francés/Barra Z Acostado.png",
        "isLocked": false
      },
      {
        "id": "barra_z_sentado",
        "name": "Barra Z Sentado",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press Francés/Barra Z Sentado.png",
        "isLocked": false
      },
      {
        "id": "mancuernas",
        "name": "Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press Francés/Mancuernas.png",
        "isLocked": false
      }
    ]
  }
];

/** All exercises that have variants (main card = base, arrows cycle variants) */
export const MANIFEST_WITH_VARIANTS = IMAGE_MANIFEST.filter(e => e.variants.length > 1);

/** Standalone exercises (single image, no variant cycling) */
export const MANIFEST_STANDALONE = IMAGE_MANIFEST.filter(e => e.variants.length <= 1);
