// AUTO-GENERATED by scripts/generateCatalog.mjs — DO NOT EDIT MANUALLY
// Run "npm run catalog" to regenerate after moving images.
// Generated: 2026-06-02T06:53:39.064Z

export interface ManifestVariant {
  id: string;
  name: string;
  imagePath: string;
  isLocked: boolean;
}

export interface ManifestExercise {
  id: string;
  name: string;
  muscle: string;
  folderName: string;
  imagePath: string;
  isLocked: boolean;
  variantGroup: string | null;
  variants: ManifestVariant[];
}

export const IMAGE_MANIFEST: ManifestExercise[] = [
  {
    "id": "abdominal_russian_twist",
    "name": "Abdominal Russian Twist",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/AbdominalRussianTwist.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "crunch_abdomen",
    "name": "Crunch",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/CrunchAbdominal.png",
    "isLocked": false,
    "variantGroup": "Crunch",
    "variants": [
      {
        "id": "crunch_abdominal",
        "name": "Crunch Abdominal",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/CrunchAbdominal.png",
        "isLocked": false
      },
      {
        "id": "crunch_abdominal_en_maquina",
        "name": "Crunch Abdominal En Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/CrunchAbdominalEnMaquina.png",
        "isLocked": false
      },
      {
        "id": "crunch_polea_alta",
        "name": "Crunch Polea Alta",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch/CrunchPoleaAlta.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "crunch_oblicuo_abdomen",
    "name": "Crunch oblicuo",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch oblicuo/Crunch oblicuo.png",
    "isLocked": false,
    "variantGroup": "Crunch oblicuo",
    "variants": [
      {
        "id": "crunch_oblicuo",
        "name": "Crunch oblicuo",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch oblicuo/Crunch oblicuo.png",
        "isLocked": false
      },
      {
        "id": "encogimientos_de_rodillas_para_abdominales",
        "name": "Encogimientos de rodillas para abdominales",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch oblicuo/Encogimientos de rodillas para abdominales.png",
        "isLocked": false
      },
      {
        "id": "gemini_generated_image_2mgqe52mgqe52mgq",
        "name": "Gemini_Generated_Image_2mgqe52mgqe52mgq",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Crunch oblicuo/Gemini_Generated_Image_2mgqe52mgqe52mgq-Photoroom.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevaciones_de_pierna_colgado",
    "name": "Elevaciones De Pierna Colgado",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/ElevacionesDePiernaColgado.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "inversos_abdomen",
    "name": "Inversos",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/Inversos/AbdominalesInversos.png",
    "isLocked": false,
    "variantGroup": "Inversos",
    "variants": [
      {
        "id": "abdominales_inversos",
        "name": "Abdominales Inversos",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Inversos/AbdominalesInversos.png",
        "isLocked": false
      },
      {
        "id": "encogimientos_de_rodillas_para_abdominales",
        "name": "Encogimientos de rodillas para abdominales",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/Inversos/Encogimientos de rodillas para abdominales.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "plancha_abdomen",
    "name": "plancha",
    "muscle": "ABDOMINALES",
    "folderName": "Abdomen",
    "imagePath": "/ejercicioimg/ejercicios/Abdomen/plancha/Plancha con flexión.png",
    "isLocked": false,
    "variantGroup": "plancha",
    "variants": [
      {
        "id": "plancha_con_flexion",
        "name": "Plancha con flexión",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/plancha/Plancha con flexión.png",
        "isLocked": false
      },
      {
        "id": "plancha",
        "name": "Plancha",
        "imagePath": "/ejercicioimg/ejercicios/Abdomen/plancha/Plancha.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_de_muneca_con_barra_sentado",
    "name": "Curl de muñeca con barra sentado",
    "muscle": "ANTEBRAZO",
    "folderName": "Antebrazo",
    "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Curl de muñeca con barra sentado.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "pronacion_antebrazo",
    "name": "Pronacion",
    "muscle": "ANTEBRAZO",
    "folderName": "Antebrazo",
    "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Pronacion/Curl de barra invertido.png",
    "isLocked": false,
    "variantGroup": "Pronacion",
    "variants": [
      {
        "id": "curl_de_barra_invertido",
        "name": "Curl de barra invertido",
        "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Pronacion/Curl de barra invertido.png",
        "isLocked": false
      },
      {
        "id": "extension_de_muneca_con_barra_sentado",
        "name": "extensión de muñeca con barra sentado",
        "imagePath": "/ejercicioimg/ejercicios/Antebrazo/Pronacion/extensión de muñeca con barra sentado.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_de_biceps_bayoneta",
    "name": "Curl De Biceps Bayoneta",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlDeBicepsBayoneta.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_normal_biceps",
    "name": "Curl Normal",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlNormal/Curl de cable en polea baja a una mano.png",
    "isLocked": false,
    "variantGroup": "CurlNormal",
    "variants": [
      {
        "id": "curl_de_cable_en_polea_baja_a_una_mano",
        "name": "Curl de cable en polea baja a una mano",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlNormal/Curl de cable en polea baja a una mano.png",
        "isLocked": false
      },
      {
        "id": "curl_de_biceps_1",
        "name": "Curl De Biceps(1)",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlNormal/CurlDeBiceps(1).png",
        "isLocked": false
      },
      {
        "id": "curl_de_biceps",
        "name": "Curl De Biceps",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlNormal/CurlDeBiceps.png",
        "isLocked": false
      },
      {
        "id": "curl_de_biceps_en_polea",
        "name": "Curl De Biceps En Polea",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlNormal/CurlDeBicepsEnPolea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "curl_spiderman",
    "name": "Curl Spiderman",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/CurlSpiderman.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "martillo_biceps",
    "name": "Martillo",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Curl Martillo cuerdas .png",
    "isLocked": false,
    "variantGroup": "Martillo",
    "variants": [
      {
        "id": "curl_martillo_cuerdas",
        "name": "Curl Martillo cuerdas",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Curl Martillo cuerdas .png",
        "isLocked": false
      },
      {
        "id": "curl_martillo_mancuernas",
        "name": "Curl Martillo Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Martillo/Curl Martillo Mancuernas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "predicador_biceps",
    "name": "Predicador",
    "muscle": "BÍCEPS",
    "folderName": "Biceps",
    "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/CurlDeBicepsPredicadorBarra.png",
    "isLocked": false,
    "variantGroup": "Predicador",
    "variants": [
      {
        "id": "curl_de_biceps_predicador_barra",
        "name": "Curl De Biceps Predicador Barra",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/CurlDeBicepsPredicadorBarra.png",
        "isLocked": false
      },
      {
        "id": "curl_de_biceps_predicador_maquina",
        "name": "Curl De Biceps Predicador Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Biceps/Predicador/CurlDeBicepsPredicadorMaquina.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "caminadoras_cardio",
    "name": "Caminadoras",
    "muscle": "CARDIO",
    "folderName": "Cardio",
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/CardioBicicleta.png",
    "isLocked": false,
    "variantGroup": "Caminadoras",
    "variants": [
      {
        "id": "cardio_bicicleta",
        "name": "Cardio Bicicleta",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/CardioBicicleta.png",
        "isLocked": false
      },
      {
        "id": "cardio_eliptica",
        "name": "Cardio Eliptica",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/CardioEliptica.png",
        "isLocked": false
      },
      {
        "id": "cardio_en_cinta",
        "name": "Cardio En Cinta",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/CardioEnCinta.png",
        "isLocked": false
      },
      {
        "id": "cardio_escalera",
        "name": "Cardio Escalera",
        "imagePath": "/ejercicioimg/ejercicios/Cardio/Caminadoras/CardioEscalera.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "cardio_saltar_cuerda",
    "name": "Cardio Saltar Cuerda",
    "muscle": "CARDIO",
    "folderName": "Cardio",
    "imagePath": "/ejercicioimg/ejercicios/Cardio/Cardio Saltar Cuerda.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "cardio_remo",
    "name": "Cardio Remo",
    "muscle": "CARDIO",
    "folderName": "Cardio",
    "imagePath": "/ejercicioimg/ejercicios/Cardio/CardioRemo.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "cardio_saltar_cuerda",
    "name": "Cardio Saltar Cuerda",
    "muscle": "CARDIO",
    "folderName": "Cardio",
    "imagePath": "/ejercicioimg/ejercicios/Cardio/CardioSaltarCuerda.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "arnes_de_cuello_neck_harness",
    "name": "Arnés de cuello (Neck Harness)",
    "muscle": "CUELLO",
    "folderName": "Cuello",
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Arnés de cuello (Neck Harness).png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "extensiones_de_cuello_con_disco",
    "name": "Extensiones de cuello con disco",
    "muscle": "CUELLO",
    "folderName": "Cuello",
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Extensiones de cuello con disco.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "flexiones_de_cuello_con_disco",
    "name": "Flexiones de cuello con disco",
    "muscle": "CUELLO",
    "folderName": "Cuello",
    "imagePath": "/ejercicioimg/ejercicios/Cuello/Flexiones de cuello con disco.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "dominadas_espalda",
    "name": "Dominadas",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Dominadas Asistidas Máquina.png",
    "isLocked": false,
    "variantGroup": "Dominadas",
    "variants": [
      {
        "id": "dominadas_asistidas_maquina",
        "name": "Dominadas Asistidas Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Dominadas Asistidas Máquina.png",
        "isLocked": false
      },
      {
        "id": "dominadas_pullups",
        "name": "Dominadas Pullups",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Dominadas/Dominadas Pullups.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "jalon_espalda",
    "name": "Jalon",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalon/Jalón al Pecho Agarre Estrecho.png",
    "isLocked": false,
    "variantGroup": "Jalon",
    "variants": [
      {
        "id": "jalon_al_pecho_agarre_estrecho",
        "name": "Jalón al Pecho Agarre Estrecho",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalon/Jalón al Pecho Agarre Estrecho.png",
        "isLocked": false
      },
      {
        "id": "jalon_al_pecho_polea_alta",
        "name": "Jalón al Pecho Polea Alta",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Jalon/Jalón al Pecho Polea Alta.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "pull_over_en_polea",
    "name": "Pull-Over en Polea",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Pull-Over en Polea.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "remo_espalda",
    "name": "Remo",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo/Remo con Barra Pendlay.png",
    "isLocked": false,
    "variantGroup": "Remo",
    "variants": [
      {
        "id": "remo_con_barra_pendlay",
        "name": "Remo con Barra Pendlay",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo/Remo con Barra Pendlay.png",
        "isLocked": false
      },
      {
        "id": "remo_con_barra_yates",
        "name": "Remo con Barra Yates",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo/Remo con Barra Yates.png",
        "isLocked": false
      },
      {
        "id": "remo_con_mancuerna_unilateral",
        "name": "Remo con Mancuerna Unilateral",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo/Remo con Mancuerna Unilateral.png",
        "isLocked": false
      },
      {
        "id": "remo_en_t_barra_maquina",
        "name": "Remo en T Barra_Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo/Remo en T Barra_Máquina.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "remo_sentado_espalda",
    "name": "Remo sentado",
    "muscle": "ESPALDA",
    "folderName": "Espalda",
    "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo sentado/Remo en Máquina Pecho Apoyado.png",
    "isLocked": false,
    "variantGroup": "Remo sentado",
    "variants": [
      {
        "id": "remo_en_maquina_pecho_apoyado",
        "name": "Remo en Máquina Pecho Apoyado",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo sentado/Remo en Máquina Pecho Apoyado.png",
        "isLocked": false
      },
      {
        "id": "remo_gironda_polea_baja",
        "name": "Remo Gironda Polea Baja",
        "imagePath": "/ejercicioimg/ejercicios/Espalda/Remo sentado/Remo Gironda Polea Baja.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevacion_de_gemelos_sentado",
    "name": "Elevación de gemelos sentado",
    "muscle": "PANTORRILLAS",
    "folderName": "Gemelos",
    "imagePath": "/ejercicioimg/ejercicios/Gemelos/Elevación de gemelos sentado.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "parado_gemelos",
    "name": "Parado",
    "muscle": "PANTORRILLAS",
    "folderName": "Gemelos",
    "imagePath": "/ejercicioimg/ejercicios/Gemelos/Parado/Elevacion de gemelos de pie en maquina .png",
    "isLocked": false,
    "variantGroup": "Parado",
    "variants": [
      {
        "id": "elevacion_de_gemelos_de_pie_en_maquina",
        "name": "Elevacion de gemelos de pie en maquina",
        "imagePath": "/ejercicioimg/ejercicios/Gemelos/Parado/Elevacion de gemelos de pie en maquina .png",
        "isLocked": false
      },
      {
        "id": "elevacion_de_gemelos_de_pie_en_smith",
        "name": "Elevacion de gemelos de pie en smith",
        "imagePath": "/ejercicioimg/ejercicios/Gemelos/Parado/Elevacion de gemelos de pie en smith .png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "abduccion_de_cadera_con_maquina_de_abduccion_de_cadera",
    "name": "Abducción de cadera con máquina de abducción de cadera",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Abducción de cadera con máquina de abducción de cadera.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "caminata_de_pato",
    "name": "Caminata de pato",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Caminata de pato.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "columpios_con_kettlebell",
    "name": "Columpios con kettlebell",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Columpios con kettlebell (2).png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "elevaciones_en_posicion_de_rana_con_propio_peso",
    "name": "Elevaciones en posición de rana con propio peso",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Elevaciones en posición de rana con propio peso.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "hip_trust_gluteo",
    "name": "Hip Trust",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/HipTrust/HiptrustBarraLibre.png",
    "isLocked": false,
    "variantGroup": "HipTrust",
    "variants": [
      {
        "id": "hiptrust_barra_libre",
        "name": "Hiptrust Barra Libre",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/HipTrust/HiptrustBarraLibre.png",
        "isLocked": false
      },
      {
        "id": "hiptrust_en_maquina",
        "name": "Hiptrust En Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/HipTrust/HiptrustEnMaquina.png",
        "isLocked": false
      },
      {
        "id": "hip_trust_ens_mith",
        "name": "Hip Trust Ens MITH",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/HipTrust/HipTrustEnsMITH.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "patada_gluteo",
    "name": "Patada",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada/PatadaDeGluteo.png",
    "isLocked": false,
    "variantGroup": "Patada",
    "variants": [
      {
        "id": "patada_de_gluteo",
        "name": "Patada De Gluteo",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada/PatadaDeGluteo.png",
        "isLocked": false
      },
      {
        "id": "patada_de_gluteo_en_maquina",
        "name": "Patada De Gluteo En Maquina",
        "imagePath": "/ejercicioimg/ejercicios/Gluteo/Patada/PatadaDeGluteoEnMaquina.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "step_up_con_mancuernas",
    "name": "Step Up con mancuernas",
    "muscle": "GLÚTEOS",
    "folderName": "Gluteo",
    "imagePath": "/ejercicioimg/ejercicios/Gluteo/Step Up con mancuernas.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "elevacion_frontal_hombro",
    "name": "Elevacion frontal",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevacion frontal/Elevaciones Frontales Mancuernas.png",
    "isLocked": false,
    "variantGroup": "Elevacion frontal",
    "variants": [
      {
        "id": "elevaciones_frontales_mancuernas",
        "name": "Elevaciones Frontales Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevacion frontal/Elevaciones Frontales Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "elevaciones_frontales_polea",
        "name": "Elevaciones Frontales Polea",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevacion frontal/Elevaciones Frontales Polea.png",
        "isLocked": false
      },
      {
        "id": "elevacion_frontal_con_disco_a_dos_manos",
        "name": "Elevación frontal con disco a dos manos",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevacion frontal/Elevación frontal con disco a dos manos.png",
        "isLocked": false
      },
      {
        "id": "elevacion_frontal_con_mancuerna_a_dos_manos",
        "name": "Elevación frontal con mancuerna a dos manos",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Elevacion frontal/Elevación frontal con mancuerna a dos manos.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "elevacion_lateral_hombro",
    "name": "elevacion lateral",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/elevacion lateral/Elevaciones Laterales Mancuernas.png",
    "isLocked": false,
    "variantGroup": "elevacion lateral",
    "variants": [
      {
        "id": "elevaciones_laterales_mancuernas",
        "name": "Elevaciones Laterales Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/elevacion lateral/Elevaciones Laterales Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "elevaciones_laterales_maquina",
        "name": "Elevaciones Laterales Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/elevacion lateral/Elevaciones Laterales Máquina.png",
        "isLocked": false
      },
      {
        "id": "elevaciones_laterales_polea",
        "name": "Elevaciones Laterales Polea",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/elevacion lateral/Elevaciones Laterales Polea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "face_pull",
    "name": "Face Pull",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Face Pull.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "militar_hombro",
    "name": "Militar",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Militar/Press de Hombros Máquina.png",
    "isLocked": false,
    "variantGroup": "Militar",
    "variants": [
      {
        "id": "press_de_hombros_maquina",
        "name": "Press de Hombros Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Militar/Press de Hombros Máquina.png",
        "isLocked": false
      },
      {
        "id": "press_militar_barra",
        "name": "Press Militar Barra",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Militar/Press Militar Barra.png",
        "isLocked": false
      },
      {
        "id": "press_militar_en_smith",
        "name": "Press militar en smith",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Militar/Press militar en smith -Photoroom.png",
        "isLocked": false
      },
      {
        "id": "press_militar_mancuernas",
        "name": "Press Militar Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Hombro/Militar/Press Militar Mancuernas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "peck_deck_invertido",
    "name": "Peck Deck Invertido",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Peck Deck Invertido.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "pajaros_vuelos_mancuernas",
    "name": "Pájaros_Vuelos Mancuernas",
    "muscle": "HOMBRO",
    "folderName": "Hombro",
    "imagePath": "/ejercicioimg/ejercicios/Hombro/Pájaros_Vuelos Mancuernas.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_femoral_sentado_maquina",
    "name": "Curl Femoral Sentado Máquina",
    "muscle": "ISQUIOTIBIALES",
    "folderName": "Isquiotibiales",
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Curl Femoral Sentado Máquina.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "curl_femoral_tumbado_maquina",
    "name": "Curl Femoral Tumbado Máquina",
    "muscle": "ISQUIOTIBIALES",
    "folderName": "Isquiotibiales",
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Curl Femoral Tumbado Máquina.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "peso_muerto_isquiotibiales",
    "name": "Peso Muerto",
    "muscle": "ISQUIOTIBIALES",
    "folderName": "Isquiotibiales",
    "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Peso muerto con barra hexagonal.png",
    "isLocked": false,
    "variantGroup": "Peso Muerto",
    "variants": [
      {
        "id": "peso_muerto_con_barra_hexagonal",
        "name": "Peso muerto con barra hexagonal",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Peso muerto con barra hexagonal.png",
        "isLocked": false
      },
      {
        "id": "peso_muerto_deadlift",
        "name": "Peso Muerto Deadlift",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Peso Muerto Deadlift.png",
        "isLocked": false
      },
      {
        "id": "peso_muerto_sumo_con_barra",
        "name": "Peso muerto sumo con barra",
        "imagePath": "/ejercicioimg/ejercicios/Isquiotibiales/Peso Muerto/Peso muerto sumo con barra.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "crude_de_polea_pecho",
    "name": "Crude de polea",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Crude de polea/CrossOverEnPoleaBaja.png",
    "isLocked": false,
    "variantGroup": "Crude de polea",
    "variants": [
      {
        "id": "cross_over_en_polea_baja",
        "name": "Cross Over En Polea Baja",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Crude de polea/CrossOverEnPoleaBaja.png",
        "isLocked": false
      },
      {
        "id": "cruce_de_poleas_alta_cross_over",
        "name": "Cruce De Poleas Alta Cross Over",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Crude de polea/CruceDePoleasAltaCrossOver.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "declinado_pecho",
    "name": "Declinado",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Declinado/PressDeclinadoEnBarra.png",
    "isLocked": false,
    "variantGroup": "Declinado",
    "variants": [
      {
        "id": "press_declinado_en_barra",
        "name": "Press Declinado En Barra",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Declinado/PressDeclinadoEnBarra.png",
        "isLocked": false
      },
      {
        "id": "press_declinado_mancuerna",
        "name": "Press Declinado Mancuerna",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Declinado/PressDeclinadoMancuerna.png",
        "isLocked": false
      },
      {
        "id": "press_inclinado_con_polea",
        "name": "Press Inclinado Con Polea",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Declinado/PressInclinadoConPolea.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "flyes_mariposa_peck_deck",
    "name": "Flyes Mariposa Peck Deck",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/FlyesMariposaPeckDeck.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "fondos_pecho_pecho",
    "name": "Fondos pecho",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos pecho/Fondos Dips.png",
    "isLocked": false,
    "variantGroup": "Fondos pecho",
    "variants": [
      {
        "id": "fondos_dips",
        "name": "Fondos Dips",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos pecho/Fondos Dips.png",
        "isLocked": false
      },
      {
        "id": "fondos_dips_asistido_pecho",
        "name": "Fondos Dips Asistido(Pecho)",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Fondos pecho/FondosDipsAsistido(Pecho).png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "inclinado_pecho",
    "name": "Inclinado",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Inclinado/PressInclinadoConBarra.png",
    "isLocked": false,
    "variantGroup": "Inclinado",
    "variants": [
      {
        "id": "press_inclinado_con_barra",
        "name": "Press Inclinado Con Barra",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Inclinado/PressInclinadoConBarra.png",
        "isLocked": false
      },
      {
        "id": "press_inclinado_con_mancuerna",
        "name": "Press Inclinado Con Mancuerna",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Inclinado/PressInclinadoConMancuerna.png",
        "isLocked": false
      },
      {
        "id": "press_inclinado_en_maquina",
        "name": "Press Inclinado En Maquina",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Inclinado/PressInclinadoEnMaquina.png",
        "isLocked": false
      },
      {
        "id": "press_inclinado_en_smith",
        "name": "Press Inclinado En Smith",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Inclinado/PressInclinadoEnSmith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "plano_pecho",
    "name": "Plano",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/Plano/PressBancaPlanoLibre.png",
    "isLocked": false,
    "variantGroup": "Plano",
    "variants": [
      {
        "id": "press_banca_plano_libre",
        "name": "Press Banca Plano Libre",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Plano/PressBancaPlanoLibre.png",
        "isLocked": false
      },
      {
        "id": "press_banca_plano_mancuerna",
        "name": "Press Banca Plano Mancuerna",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Plano/PressBancaPlanoMancuerna.png",
        "isLocked": false
      },
      {
        "id": "press_plano_en_maquina",
        "name": "Press Plano En Maquina",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Plano/PressPlanoEnMaquina.png",
        "isLocked": false
      },
      {
        "id": "press_plano_en_smith",
        "name": "Press Plano En Smith",
        "imagePath": "/ejercicioimg/ejercicios/pecho/Plano/PressPlanoEnSmith.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "press_declinado_en_maquina",
    "name": "Press Declinado En Maquina",
    "muscle": "PECHO",
    "folderName": "pecho",
    "imagePath": "/ejercicioimg/ejercicios/pecho/PressDeclinadoEnMaquina.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "extensiones_de_cuadriceps",
    "name": "Extensiones de Cuádriceps",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Extensiones de Cuádriceps.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "good_mornings_buenos_dias",
    "name": "Good Mornings Buenos Días",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Good Mornings Buenos Días.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "prensa_de_piernas_45",
    "name": "Prensa de Piernas 45°",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Prensa de Piernas 45°.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "sentadilla_pierna",
    "name": "Sentadilla",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Sentadilla Frontal.png",
    "isLocked": false,
    "variantGroup": "Sentadilla",
    "variants": [
      {
        "id": "sentadilla_frontal",
        "name": "Sentadilla Frontal",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Sentadilla Frontal.png",
        "isLocked": false
      },
      {
        "id": "sentadilla_hack_maquina",
        "name": "Sentadilla Hack Máquina",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Sentadilla Hack Máquina.png",
        "isLocked": false
      },
      {
        "id": "sentadilla_libre_barra",
        "name": "Sentadilla Libre Barra",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Sentadilla/Sentadilla Libre Barra.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "zancadas_pierna",
    "name": "Zancadas",
    "muscle": "CUÁDRICEPS",
    "folderName": "Pierna",
    "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Sentadilla Bulgara.png",
    "isLocked": false,
    "variantGroup": "Zancadas",
    "variants": [
      {
        "id": "sentadilla_bulgara",
        "name": "Sentadilla Bulgara",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Sentadilla Bulgara.png",
        "isLocked": false
      },
      {
        "id": "zancadas_con_smith",
        "name": "Zancadas con smith",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Zancadas con smith.png",
        "isLocked": false
      },
      {
        "id": "zancadas_lunges_con_barra",
        "name": "Zancadas_Lunges con Barra",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Zancadas_Lunges con Barra.png",
        "isLocked": false
      },
      {
        "id": "zancadas_lunges_con_mancuernas",
        "name": "Zancadas_Lunges con Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Pierna/Zancadas/Zancadas_Lunges con Mancuernas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "encogimientos_de_hombros_con_barra",
    "name": "Encogimientos de hombros con barra",
    "muscle": "ESPALDA",
    "folderName": "Trapecios",
    "imagePath": "/ejercicioimg/ejercicios/Trapecios/Encogimientos de hombros con barra.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "encogimientos_de_hombros_con_mancuernas",
    "name": "Encogimientos de hombros con mancuernas",
    "muscle": "ESPALDA",
    "folderName": "Trapecios",
    "imagePath": "/ejercicioimg/ejercicios/Trapecios/Encogimientos de hombros con mancuernas.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "copa_triceps",
    "name": "copa",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/copa/Copa a dos manos Mancuerna.png",
    "isLocked": false,
    "variantGroup": "copa",
    "variants": [
      {
        "id": "copa_a_dos_manos_mancuerna",
        "name": "Copa a dos manos Mancuerna",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/copa/Copa a dos manos Mancuerna.png",
        "isLocked": false
      },
      {
        "id": "copa_a_una_mano_mancuerna",
        "name": "Copa a una mano Mancuerna",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/copa/Copa a una mano Mancuerna.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "extension_tricep_triceps",
    "name": "Extension tricep",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Extension tricep/Extensiones de Tríceps Cuerda.png",
    "isLocked": false,
    "variantGroup": "Extension tricep",
    "variants": [
      {
        "id": "extensiones_de_triceps_cuerda",
        "name": "Extensiones de Tríceps Cuerda",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Extension tricep/Extensiones de Tríceps Cuerda.png",
        "isLocked": false
      },
      {
        "id": "extension_de_triceps_con_cable_a_una_mano",
        "name": "Extensión de tríceps con cable a una mano",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Extension tricep/Extensión de tríceps con cable a una mano.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "fondos_triceps",
    "name": "Fondos",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Fondos en Bancos.png",
    "isLocked": false,
    "variantGroup": "Fondos",
    "variants": [
      {
        "id": "fondos_en_bancos",
        "name": "Fondos en Bancos",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Fondos en Bancos.png",
        "isLocked": false
      },
      {
        "id": "fondos_en_paralelas",
        "name": "Fondos en Paralelas",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Fondos/Fondos en Paralelas.png",
        "isLocked": false
      }
    ]
  },
  {
    "id": "patada_de_triceps_mancuerna",
    "name": "Patada de Tríceps Mancuerna",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Patada de Tríceps Mancuerna.png",
    "isLocked": false,
    "variantGroup": null,
    "variants": []
  },
  {
    "id": "press_frances_triceps",
    "name": "Press frances",
    "muscle": "TRÍCEPS",
    "folderName": "Triceps",
    "imagePath": "/ejercicioimg/ejercicios/Triceps/Press frances/Press Francés Barra Z.png",
    "isLocked": false,
    "variantGroup": "Press frances",
    "variants": [
      {
        "id": "press_frances_barra_z",
        "name": "Press Francés Barra Z",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press frances/Press Francés Barra Z.png",
        "isLocked": false
      },
      {
        "id": "press_frances_mancuernas",
        "name": "Press Francés Mancuernas",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press frances/Press Francés Mancuernas.png",
        "isLocked": false
      },
      {
        "id": "press_frances_sentado_con_barra",
        "name": "Press francés sentado con barra",
        "imagePath": "/ejercicioimg/ejercicios/Triceps/Press frances/Press francés sentado con barra.png",
        "isLocked": false
      }
    ]
  }
];

/** All exercises that have variants (main card = base, arrows cycle variants) */
export const MANIFEST_WITH_VARIANTS = IMAGE_MANIFEST.filter(e => e.variants.length > 1);

/** Standalone exercises (single image, no variant cycling) */
export const MANIFEST_STANDALONE = IMAGE_MANIFEST.filter(e => e.variants.length <= 1);
